"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";

/**
 * Language Context - Quản lý đa ngôn ngữ (ZH/EN/VI/DE/ES)
 */

const translations = {
  en: {
    nav: {
      home: "Home",
      products: "Products",
      company: "Company",
      news: "News",
      support: "Support",
      contact: "Contact Us",
      aboutUs: "About Us",
      solutions: "Solution",
      productsCenter: "Product Center",
      rnd: "R&D and Manufacturing",
      solutionHousehold: "Household Energy Storage Solutions",
      solutionCommercial: "Industrial and Commercial Energy Storage",
      solutionPhotovoltaic: "Photovoltaic System Solutions",
      rndCapabilities: "R&D Capabilities",
      batchProduction: "Batch production capabilities",
      qualityAssurance: "Quality assurance",
      technicalSupport: "Technical Support",
      postSale: "After-sales service",
      dataDownload: "Data download",
    },
    home: {
      heroTitle: "Powering the Future with Clean Energy",
      heroSubtitle:
        "Leading manufacturer of high-efficiency solar inverters and energy storage systems",
      cta: "Explore Products",
      ctaSecondary: "Contact Us",
      globalDesign: "Global layout",
      powerConverterLeader: "Become a leader in power electronic converters",
      heroTitle2: "Innovation driven green empowerment",
      heroSubtitle2: "Provide clean energy solutions for the world",
      solutionsTitle: "Solution",
      solutionsSubtitle: "Multiple working modes, can flexibly respond to various scenarios!",
      householdSolutionTitle: "Household energy storage solutions",
      householdSolutionDescription:
        "We offer hybrid inverters and household batteries with high power density, high conversion efficiency, reliable protection, intelligence, and stability for home energy saving, villa power supply, balcony solar, data centers, and remote islands.",
      commercialSolutionTitle: "Industrial and Commercial Energy Storage",
      commercialSolutionDescription: "We provide modular energy storage converters with various power specifications, C&I energy storage converter and system, EMS and other key equipments and integrated solutions, to meet the needs of auxiliary service, peak-load shifting, demand side response, dynamic capacity expansion, etc.",
      photovoltaicSolutionTitle: "Photovoltaic System Solutions",
      photovoltaicSolutionDescription: "We offer PV inverters ranging from 10 to 110 kW, featuring high efficiency, intelligent stability, and reliable safety. These inverters are suitable for various scenarios, including residential, distributed, and large-scale photovoltaic power plants.",
      rndTitle: "R&D and Manufacturing",
      rndSubtitle: "Research and innovation, forging the future of electricity",
      rndParagraph1: "Always regard quality as the core of survival and development.",
      rndParagraph2: "Has passed the ISO9001 international quality management system certification.",
      rndParagraph3: "Multiple international certifications such as ISO 14001 environmental management system certification.",
      corporateNews: "Corporate News",
      recommendedProducts: "Recommended Products",
      recommendedSubtitle: "Safe, reliable, efficient, one-stop energy solution",
    },
    products: {
      title: "Our Products",
      subtitle: "Innovative solutions for every solar application",
      viewDetails: "View Details",
      allCategories: "All Categories",
      allProducts: "All Products",
      loading: "Loading products...",
      noProducts: "No products found in this category.",
      detailNotFound: "Product Not Found",
      backToProducts: "Back to Products",
      productImage: "Product Image",
      keyFeatures: "Key Features",
      requestQuote: "Request a Quote",
      downloadDatasheet: "Download Datasheet",
      pvInverters: "Photovoltaic System",
      energyStorage: "Industrial and Commercial Energy Storage",
      hybridInverters: "Household Energy Storage",
      parameter: "Parameter",
      manual: "Manual",
      positionPrefix: "Position: Home > Product Center > ",
      productAdvantages: "Product Advantages",
      technicalSpecifications: "Technical Specifications",
      productModel: "Product model",
      specificationsData: "Specifications Data",
      recommendedProducts: "Recommended Products",
      more: "MORE",
    },
    company: {
      title: "About Us",
      subtitle: "15+ years of innovation in renewable energy",
      heroTitle: "About UNC Technology",
      heroSubtitle: "UNC a new driving force for green energy",
      storyTitle: "Company Introduction",
      introP1: "Qingdao Uni-Convtor Technology Co., Ltd (UNC), established in 2021, has been deeply engaged in the renewable energy industry, focusing on R&D and application of power-supply conversion technology.",
      introP2: "Our product range covers household hybrid inverters, PV inverters, and energy storage PCS. These products are trusted in domestic and international markets.",
      introP3: "UNC has built an intelligent factory covering more than 10,000 square meters. Annual production capacity reaches up to 400,000 sets.",
      introP4: "UNC is committed to becoming a leader in global power electronic converters.",
      cultureTitle: "Corporate Culture",
      partnerCta: "Partner With Us",
      journeyTitle: "Milestone",
      certificationsTitle: "Honor",
      certificationsSubtitle: "International quality and product certifications",
      milestone2021: "Qingdao Uni-Convtor Technology Co., Ltd was established.",
      milestone2022: "Core R&D and manufacturing team expanded across power conversion fields.",
      milestone2023: "Household hybrid inverter and energy storage products entered batch production.",
      milestone2024: "Global product portfolio expanded across household, C&I, and photovoltaic systems.",
      milestone2025: "UNC continued international certification and global market development.",
    },
    contact: {
      title: "Contact Us",
      subtitle: "Get in touch with our team",
      name: "Full Name",
      email: "Email Address",
      phone: "Phone Number",
      subject: "Subject",
      message: "Message",
      send: "Submit",
      interesting: "Interesting",
      company: "Company",
      address: "Address",
      verify: "verify",
      clickVerify: "Click to verify",
      heroSubtitle:
        "Get in touch with our sales and technical team. We're here to help you find the right solution.",
      information: "Contact Information",
      businessHours: "Business Hours",
      mondayFriday: "Monday - Friday",
      saturday: "Saturday",
      sunday: "Sunday",
      closed: "Closed",
      sendUsMessage: "Send Us a Message",
      success:
        "Your message has been sent successfully! We'll get back to you within 24 hours.",
      error: "Failed to send message. Please try again later.",
      sending: "Sending...",
      namePlaceholder: "John Doe",
      emailPlaceholder: "john@company.com",
      subjectPlaceholder: "Product Inquiry",
      messagePlaceholder: "Tell us about your project requirements...",
    },
    common: {
      learnMore: "Learn More",
      readMore: "Read More",
      download: "Download",
      loading: "Loading...",
      more: "More",
      new: "NEW",
      selectLanguage: "Select language",
      toggleMenu: "Toggle menu",
    },
    news: {
      title: "News & Updates",
      subtitle:
        "Stay informed with the latest product launches, certifications, and industry insights.",
      noArticles: "No news articles available.",
      productLaunch: "Product Launch",
      certification: "Certification",
      industryNews: "Industry News",
      partnership: "Partnership",
      events: "Events",
    },
    newsData: {
      "news-483": {
        title: "Unleash Energy Independence with UNC Technology's All-in-One PV & Battery System!",
        excerpt: "UNC Technology presents an integrated photovoltaic and battery system for residential clean energy independence.",
        content: "UNC Technology's all-in-one photovoltaic and battery system is designed to simplify household clean-energy deployment. The system combines PV generation, storage, and intelligent control to help customers improve self-consumption and continuity of power supply."
      },
      "news-480": {
        title: "UNC Unveils Energy Solutions at SNEC PV Power Expo 2025",
        excerpt: "UNC showcased residential, commercial, and photovoltaic energy solutions at SNEC PV Power Expo 2025.",
        content: "At SNEC PV Power Expo 2025, UNC demonstrated its hybrid inverter, energy storage, and photovoltaic inverter portfolio for global partners and customers."
      },
      "solar-inverter-74": {
        title: "Technical Characteristics of Hybrid Solar Power Inverters",
        excerpt: "Hybrid solar power inverters integrate PV generation, battery storage, and grid interaction in one system.",
        content: "Hybrid solar power inverters support PV conversion, battery charge and discharge, backup output, and intelligent energy scheduling. These features make them suitable for household and commercial clean-energy scenarios."
      },
      "central-pv-inverter-73": {
        title: "Advantages and Disadvantages of Central PV Inverters",
        excerpt: "Central PV inverters support large power conversion with centralized operation and maintenance.",
        content: "Central PV inverters are often used in large-scale power stations where centralized conversion can simplify operation. System design should also account for redundancy, maintenance, and site-level reliability."
      },
      "off-grid-hybrid-inverter-72": {
        title: "What are the Application Scenarios for Off Grid Hybrid Inverters?",
        excerpt: "Off-grid hybrid inverters are suitable for remote sites, backup power, and energy independence.",
        content: "Off-grid hybrid inverters can combine PV generation, storage batteries, and generator support to provide stable power in remote islands, villas, and backup supply scenarios."
      },
      "energy-storage-system-71": {
        title: "Functions and Roles of Residential Energy Storage Systems",
        excerpt: "Residential energy storage systems improve self-consumption, backup capacity, and energy management.",
        content: "Residential energy storage systems store surplus PV generation and dispatch electricity when needed. They can reduce grid dependency, support critical loads, and improve household energy resilience."
      },
      "solar-storage-companies-70": {
        title: "Business Model and Technology Direction of Solar Storage Companies",
        excerpt: "Solar storage companies combine energy storage products with system-level service capabilities.",
        content: "Solar storage companies continue to expand integrated products, intelligent monitoring, and service-oriented energy solutions for residential and commercial applications."
      },
      "solar-charge-inverter-69": {
        title: "What are the Different Types of Solar Charge Inverters?",
        excerpt: "Solar charge inverters vary by topology, power range, and grid interaction modes.",
        content: "Solar charge inverters can support off-grid, hybrid, and grid-connected scenarios, helping users adapt photovoltaic generation to different energy usage needs."
      },
      "pv-panel-inverter-68": {
        title: "Types and Characteristics of PV Panel Inverters",
        excerpt: "PV panel inverters provide efficient conversion and monitoring for photovoltaic power generation.",
        content: "PV panel inverter selection depends on application size, MPPT range, protection level, and site operation requirements."
      }
    },
    rnd: {
      pageTitle: "R&D and Manufacturing",
      pageSubtitle: "Always regard quality as the core of survival and development.",
      researchSubtitle: "The R&D team of UNC consists of more than 30 senior experts",
      researchText: "The UNC R&D team covers software, hardware, algorithms, structure, and electrical design. The team has successfully developed energy storage converters and PV inverters.",
      doctoralDegree: "Doctoral degree",
      masterDegree: "Master's degree",
      patent: "Patent",
      industryExperience: "Power electronics industry experience",
      standard: "Standard",
      produceSubtitle: "Advanced production facilities efficiently support and guarantee manufacturing capability.",
      produceText: "UNC has independent integrated assembly production lines for energy storage products, residential hybrid inverters, and self-developed 3S systems: PCS, BMS, and EMS.",
      labArea: "The laboratory area is over 400 square meters",
      hybridDev: "Development of hybrid inverter products of 30kW and below",
      pcsDev: "Development of PCS products of 630kW and below",
      pvDev: "Development of products with specifications of 110kW and below",
      workshopAlt: "UNC production workshop",
      qualitySubtitle: "UNC has obtained ISO9001 and ISO14001 certifications.",
      qualityText: "Quality is the core of the company's survival and sustainable development. UNC has established a rigorous and efficient quality management system.",
      qualityRD: "R&D guarantee",
      qualityRDText: "Senior electronics engineers with over 10 years of field experience lead the R&D team.",
      qualityAfterSale: "After-sale services",
      qualityAfterSaleText: "A comprehensive after-sales service system covers technical support, repair services, and spare parts supply.",
      qualityInspection: "Quality Inspection",
      qualityInspectionText: "Strict quality management monitors raw material procurement, production process control, and final product inspection.",
      qualityProduction: "Production Quality control",
      qualityProductionText: "The intelligent workshop uses advanced production facilities and processes to ensure stable quality.",
    },
    support: {
      pageTitle: "Technical Support",
      pageSubtitle: "With multiple working modes, UNC Energy Storage can flexibly respond to various scenarios.",
      techText1: "UNC's technical support process follows the principles of \"rapid response, professional handling, and full tracking.\" With deep industry background and extensive technical experience, UNC is committed to offering efficient and precise technical support services.",
      techServicesTitle: "Technical support services",
      afterSalesText: "The after-sales service team at UNC is composed of experienced and highly skilled engineers who can respond swiftly to customer needs.",
      title: "Technical Support",
      subtitle: "Access product documentation, downloads, training resources, and expert technical support.",
      directTitle: "Need Direct Support?",
      directText: "Our technical support team is available to help you with installation, commissioning, and troubleshooting.",
      contactTeam: "Contact Support Team",
      callHotline: "Call Hotline",
      datasheetsTitle: "Product Datasheets",
      datasheetsDescription: "Download detailed technical specifications and datasheets for all our products.",
      datasheetsAction: "Browse Datasheets",
      manualsTitle: "Installation Manuals",
      manualsDescription: "Step-by-step installation guides and wiring diagrams for safe and efficient product setup.",
      manualsAction: "View Manuals",
      softwareTitle: "Software & Firmware",
      softwareDescription: "Download the latest monitoring software, firmware updates, and configuration tools.",
      softwareAction: "Download Software",
      videosTitle: "Video Tutorials",
      videosDescription: "Watch installation walkthroughs, troubleshooting guides, and product demonstration videos.",
      videosAction: "Watch Videos",
      faqTitle: "FAQ",
      faqDescription: "Find answers to the most commonly asked questions about our products and services.",
      faqAction: "View FAQ",
      trainingTitle: "Training Programs",
      trainingDescription: "Register for online and in-person technical training sessions for installers and engineers.",
      trainingAction: "Register Now",
    },
    footer: {
      contactNow: "Contact Us Now",
      name: "Name",
      telephone: "Telephone",
      counseling: "Counseling",
      sending: "Sending",
      hotline: "Hotline",
    },
  },
  vi: {
    nav: {
      home: "Trang chủ",
      products: "Sản phẩm",
      company: "Công ty",
      news: "Tin tức",
      support: "Hỗ trợ",
      contact: "Liên hệ",
      aboutUs: "Về chúng tôi",
      solutions: "Giải pháp",
      productsCenter: "Trung tâm sản phẩm",
      rnd: "R&D và sản xuất",
      solutionHousehold: "Giải pháp lưu trữ năng lượng gia đình",
      solutionCommercial: "Lưu trữ năng lượng thương mại và công nghiệp",
      solutionPhotovoltaic: "Giải pháp hệ thống quang điện",
      rndCapabilities: "Năng lực R&D",
      batchProduction: "Năng lực sản xuất hàng loạt",
      qualityAssurance: "Đảm bảo chất lượng",
      technicalSupport: "Hỗ trợ kỹ thuật",
      postSale: "Dịch vụ sau bán hàng",
      dataDownload: "Tải dữ liệu",
    },
    home: {
      heroTitle: "Kiến tạo tương lai với năng lượng sạch",
      heroSubtitle:
        "Nhà sản xuất hàng đầu biến tần năng lượng mặt trời và hệ thống lưu trữ năng lượng",
      cta: "Khám phá sản phẩm",
      ctaSecondary: "Liên hệ",
      globalDesign: "Sơ đồ toàn cầu",
      powerConverterLeader: "",

      heroSubtitle2: "Cung cấp các giải pháp năng lượng sạch cho thế giới",
      solutionsTitle: "Giải pháp",
      solutionsSubtitle: "Nhiều chế độ vận hành giúp đáp ứng linh hoạt các kịch bản khác nhau.",
      householdSolutionTitle: "Giải pháp lưu trữ năng lượng gia đình",
      householdSolutionDescription:
        "Chúng tôi cung cấp biến tần hybrid và pin gia đình có mật độ công suất cao, hiệu suất chuyển đổi cao, khả năng bảo vệ tin cậy, thông minh và ổn định cho nhiều nhu cầu sử dụng trong gia đình.",
      commercialSolutionTitle: "Lưu trữ năng lượng thương mại và công nghiệp",
      commercialSolutionDescription: "Chúng tôi cung cấp hệ thống lưu trữ năng lượng dạng mô-đun với nhiều mức công suất đa dạng, hệ thống và bộ chuyển đổi lưu trữ C&I, giải pháp EMS, nhằm đáp ứng các nhu cầu như dịch vụ phụ trợ, cạo đỉnh lấp đáy, phản ứng theo nhu cầu, và mở rộng công suất động, v.v.",
      photovoltaicSolutionTitle: "Giải pháp hệ thống quang điện",
      photovoltaicSolutionDescription: "Chúng tôi mang đến các dòng biến tần PV công suất từ 10 đến 110kW với hiệu suất cao, vận hành thông minh và an toàn vượt trội, phù hợp cho nhiều mô hình: từ dân dụng, điện mặt trời phân tán đến các nhà máy điện mặt trời quy mô lớn.",
      rndTitle: "R&D và sản xuất",
      rndSubtitle: "Nghiên cứu và đổi mới, kiến tạo tương lai ngành điện",
      rndParagraph1: "Chúng tôi luôn xem chất lượng là nền tảng sống còn và phát triển.",
      rndParagraph2: "Doanh nghiệp đã đạt chứng nhận hệ thống quản lý chất lượng quốc tế ISO 9001.",
      rndParagraph3: "Sở hữu nhiều chứng nhận quốc tế, bao gồm hệ thống quản lý môi trường ISO 14001.",
      corporateNews: "Tin tức doanh nghiệp",
      recommendedProducts: "Sản phẩm nổi bật",
      recommendedSubtitle: "An toàn, tin cậy, hiệu quả, giải pháp năng lượng toàn diện",
    },
    products: {
      title: "Sản phẩm",
      subtitle: "Giải pháp sáng tạo cho mọi ứng dụng năng lượng mặt trời",
      viewDetails: "Xem chi tiết",
      allCategories: "Tất cả danh mục",
      allProducts: "Tất cả sản phẩm",
      loading: "Đang tải sản phẩm...",
      noProducts: "Không tìm thấy sản phẩm trong danh mục này.",
      detailNotFound: "Không tìm thấy sản phẩm",
      backToProducts: "Quay lại sản phẩm",
      productImage: "Hình ảnh sản phẩm",
      keyFeatures: "Tính năng chính",
      requestQuote: "Yêu cầu báo giá",
      downloadDatasheet: "Tải datasheet",
      technicalSpecifications: "Thông số kỹ thuật",
      pvInverters: "Hệ thống quang điện",
      energyStorage: "Lưu trữ năng lượng thương mại & công nghiệp",
      hybridInverters: "Lưu trữ năng lượng gia đình",
      parameter: "Thông số",
      manual: "Hướng dẫn",
      positionPrefix: "Vị trí: Trang chủ > Trung tâm sản phẩm > ",
      productAdvantages: "Ưu điểm sản phẩm",
      productModel: "Mô hình sản phẩm",
      specificationsData: "Dữ liệu thông số",
      recommendedProducts: "Sản phẩm được đề xuất",
      more: "XEM THÊM",
    },
    company: {
      title: "Về chúng tôi",
      subtitle: "15+ năm đổi mới trong năng lượng tái tạo",
      heroTitle: "Về UNC Technology",
      heroSubtitle: "UNC - Động lực xanh mới cho năng lượng",
      storyTitle: "Giới thiệu công ty",
      introP1: "Công ty TNHH Công nghệ Uni-Convtor Thanh Đảo (UNC), thành lập năm 2021, chuyên nghiên cứu và ứng dụng công nghệ chuyển đổi nguồn điện trong lĩnh vực năng lượng tái tạo.",
      introP2: "Sản phẩm gồm biến tần hybrid gia đình, biến tần quang điện và PCS lưu trữ năng lượng, được tin dùng tại thị trường trong và ngoài nước.",
      introP3: "UNC đã xây dựng nhà máy thông minh rộng hơn 10.000 m², công suất sản xuất hàng năm lên tới 400.000 bộ.",
      introP4: "UNC cam kết trở thành đơn vị dẫn đầu toàn cầu về bộ chuyển đổi điện tử công suất.",
      cultureTitle: "Văn hóa doanh nghiệp",
      partnerCta: "Hợp tác với chúng tôi",
      journeyTitle: "Cột mốc",
      certificationsTitle: "Vinh dự",
      certificationsSubtitle: "Các chứng nhận chất lượng và sản phẩm quốc tế",
      milestone2021: "Công ty TNHH Công nghệ Uni-Convtor Thanh Đảo được thành lập.",
      milestone2022: "Nhóm R&D và sản xuất cốt lõi mở rộng trong lĩnh vực chuyển đổi điện.",
      milestone2023: "Biến tần hybrid gia đình và sản phẩm lưu trữ năng lượng đi vào sản xuất hàng loạt.",
      milestone2024: "Danh mục sản phẩm toàn cầu mở rộng sang gia đình, thương mại và hệ thống quang điện.",
      milestone2025: "UNC tiếp tục chứng nhận quốc tế và phát triển thị trường toàn cầu.",
    },
    contact: {
      title: "Liên hệ",
      subtitle: "Liên hệ với đội ngũ của chúng tôi",
      name: "Họ và tên",
      email: "Email",
      phone: "Số điện thoại",
      subject: "Chủ đề",
      message: "Nội dung",
      send: "Gửi",
      interesting: "Sản phẩm quan tâm",
      company: "Công ty",
      address: "Địa chỉ",
      verify: "Xác nhận",
      clickVerify: "Nhấn để xác nhận",
      heroSubtitle: "Liên hệ với đội ngũ kinh doanh và kỹ thuật để được tư vấn giải pháp phù hợp.",
      information: "Thông tin liên hệ",
      businessHours: "Giờ làm việc",
      mondayFriday: "Thứ Hai - Thứ Sáu",
      saturday: "Thứ Bảy",
      sunday: "Chủ Nhật",
      closed: "Đóng cửa",
      sendUsMessage: "Gửi tin nhắn cho chúng tôi",
      success: "Tin nhắn của bạn đã được gửi thành công! Chúng tôi sẽ phản hồi trong vòng 24 giờ.",
      error: "Gửi tin nhắn thất bại. Vui lòng thử lại sau.",
      sending: "Đang gửi...",
      namePlaceholder: "Nguyễn Văn A",
      emailPlaceholder: "email@congty.com",
      subjectPlaceholder: "Tư vấn sản phẩm",
      messagePlaceholder: "Hãy cho chúng tôi biết yêu cầu dự án của bạn...",
    },
    common: {
      learnMore: "Tìm hiểu thêm",
      readMore: "Đọc thêm",
      download: "Tải xuống",
      loading: "Đang tải...",
      more: "Xem thêm",
      new: "MỚI",
      selectLanguage: "Chọn ngôn ngữ",
      toggleMenu: "Mở menu",
    },
    news: {
      title: "Tin tức và cập nhật",
      subtitle: "Cập nhật các sản phẩm mới, chứng nhận và xu hướng ngành.",
      noArticles: "Chưa có bài viết tin tức.",
      productLaunch: "Ra mắt sản phẩm",
      certification: "Chứng nhận",
      industryNews: "Tin ngành",
      partnership: "Hợp tác",
      events: "Sự kiện",
    },
    newsData: {
      "news-483": {
        title: "Khai Phóng Sự Độc Lập Năng Lượng Cùng Hệ Thống Lưu Trữ & Quang Điện Tích Hợp Của UNC Technology!",
        excerpt: "UNC Technology giới thiệu hệ thống quang điện và lưu trữ tích hợp để đạt được độc lập năng lượng sạch cho dân cư.",
        content: "Hệ thống điện năng lượng mặt trời và pin tích hợp tất cả trong một của UNC Technology được thiết kế để đơn giản hóa việc triển khai năng lượng sạch tại nhà. Hệ thống kết hợp phát điện PV, lưu trữ và điều khiển thông minh để giúp khách hàng tăng cường khả năng tự tiêu dùng và duy trì nguồn cung điện liên tục."
      },
      "news-480": {
        title: "UNC Ra Mắt Các Giải Pháp Năng Lượng Tại Triển Lãm SNEC 2025",
        excerpt: "UNC đã trưng bày các giải pháp năng lượng gia dụng, thương mại và quang điện tại SNEC Expo 2025.",
        content: "Tại SNEC 2025, UNC đã giới thiệu danh mục biến tần hybrid, lưu trữ năng lượng và biến tần quang điện cho các đối tác toàn cầu."
      },
      "solar-inverter-74": {
        title: "Đặc Điểm Kỹ Thuật Của Biến Tần Năng Lượng Mặt Trời Hybrid",
        excerpt: "Biến tần năng lượng mặt trời hybrid tích hợp phát điện PV, lưu trữ pin và tương tác lưới điện trong một hệ thống.",
        content: "Biến tần năng lượng mặt trời hybrid hỗ trợ chuyển đổi PV, sạc/xả pin, ngõ ra dự phòng và điều phối năng lượng thông minh. Các tính năng này giúp chúng phù hợp với ứng dụng năng lượng sạch gia đình và thương mại."
      },
      "central-pv-inverter-73": {
        title: "Ưu Và Nhược Điểm Của Biến Tần PV Trung Tâm",
        excerpt: "Biến tần PV trung tâm hỗ trợ chuyển đổi công suất lớn giúp tập trung vận hành và bảo trì.",
        content: "Biến tần PV trung tâm thường được dùng trong quy mô nhà máy điện lớn giúp vận hành thuận tiện. Tuy nhiên cũng cần thiết kế dự phòng đảm bảo tính tin cậy cao."
      },
      "off-grid-hybrid-inverter-72": {
        title: "Các Kịch Bản Ứng Dụng Biến Tần Hybrid Độc Lập Chạy Không Lưới Là Gì?",
        excerpt: "Biến tần hybrid độc lập phù hợp khu vực xa xôi, nguồn dự phòng và độc lập điện năng.",
        content: "Biến tần off-grid có thể kết hợp năng lượng mặt trời, pin và máy phát điện để cung cấp nguồn ổn định cho hải đảo, biệt thự và dự phòng."
      },
      "energy-storage-system-71": {
        title: "Chức Năng và Vai Trò của Hệ Thống Lưu Trữ Năng Lượng Gia Đình",
        excerpt: "Hệ thống lưu trữ giúp tăng khả năng tự tiêu dùng, lưu trữ dự phòng và quản lý năng lượng.",
        content: "Hệ thống này tích trữ năng lượng PV dư thừa và tiêu thụ lúc cần thiết, giảm phụ thuộc vào lưới điện và bảo vệ các tải thiết yếu."
      },
      "solar-storage-companies-70": {
        title: "Mô Hình Kinh Doanh Và Định Hướng Công Nghệ Của Doanh Nghiệp Lưu Trữ Năng Lượng",
        excerpt: "Các công ty kết hợp giải pháp lưu trữ năng lượng cùng dịch vụ vận hành toàn diện.",
        content: "Họ tạo ra sản phẩm tích hợp, giám sát thông minh và giải pháp tập trung vào dân dụng và thương mại."
      },
      "solar-charge-inverter-69": {
        title: "Các Loại Biến Tần Sạc Năng Lượng Mặt Trời Khác Nhau Là Gì?",
        excerpt: "Biến tần sạc khác nhau về ứng dụng, phạm vi công suất và chế độ lưới điện.",
        content: "Biến tần hỗ trợ không nối lưới, nối lưới hoặc hybrid, giúp khách hàng đa dạng hoá nhu cầu tiêu thụ quang điện."
      },
      "pv-panel-inverter-68": {
        title: "Phân Loại Và Đặc Điểm Của Biến Tần Quang Điện (PV Inverter)",
        excerpt: "Biến tần cho bảng năng lượng cung cấp chuyển đổi PV và giám sát tiện lợi.",
        content: "Lựa chọn biến tần PV phụ thuộc vào kích cỡ hệ thống, dải theo dõi vùng công suất MPPT và yêu cầu mức bảo vệ."
      }
    },
    rnd: {
      pageTitle: "R&D và Sản xuất",
      pageSubtitle: "Luôn xem chất lượng là nền tảng sống còn và phát triển.",
      researchSubtitle: "Đội R&D của UNC gồm hơn 30 chuyên gia cấp cao",
      researchText: "Đội R&D của UNC bao gồm phần mềm, phần cứng, thuật toán, kết cấu và thiết kế điện. Đã phát triển thành công bộ tích trữ năng lượng và biến tần quang điện.",
      doctoralDegree: "Tiến sĩ",
      masterDegree: "Thạc sĩ",
      patent: "Bằng sáng chế",
      industryExperience: "Kinh nghiệm ngành điện tử công suất",
      standard: "Tiêu chuẩn",
      produceSubtitle: "Cơ sở sản xuất tiên tiến hỗ trợ và đảm bảo năng lực sản xuất.",
      produceText: "UNC có dây chuyền lắp ráp tích hợp độc lập cho sản phẩm lưu trữ năng lượng, biến tần hybrid gia đình và hệ thống 3S tự phát triển: PCS, BMS, EMS.",
      labArea: "Diện tích phòng lab hơn 400 m²",
      hybridDev: "Phát triển sản phẩm biến tần hybrid 30kW trở xuống",
      pcsDev: "Phát triển sản phẩm PCS 630kW trở xuống",
      pvDev: "Phát triển sản phẩm 110kW trở xuống",
      workshopAlt: "Xưởng sản xuất UNC",
      qualitySubtitle: "UNC đã đạt chứng nhận ISO9001 và ISO14001.",
      qualityText: "Chất lượng là nền tảng sống còn và phát triển của công ty. UNC đã xây dựng hệ thống quản lý chất lượng nghiêm ngặt và hiệu quả.",
      qualityRD: "Đảm bảo R&D",
      qualityRDText: "Kỹ sư điện tử cấp cao với hơn 10 năm kinh nghiệm dẫn dắt đội R&D.",
      qualityAfterSale: "Dịch vụ sau bán hàng",
      qualityAfterSaleText: "Hệ thống dịch vụ hậu mãi toàn diện bao gồm hỗ trợ kỹ thuật, dịch vụ sửa chữa và cung cấp phụ tùng.",
      qualityInspection: "Kiểm tra chất lượng",
      qualityInspectionText: "Quản lý chất lượng nghiêm ngặt giám sát thu mua nguyên vật liệu, kiểm soát quy trình sản xuất và kiểm tra sản phẩm cuối.",
      qualityProduction: "Kiểm soát chất lượng sản xuất",
      qualityProductionText: "Xưởng thông minh sử dụng cơ sở sản xuất và quy trình tiên tiến để đảm bảo chất lượng ổn định.",
    },
    support: {
      pageTitle: "Hỗ trợ kỹ thuật",
      pageSubtitle: "Với nhiều chế độ hoạt động, UNC Energy Storage có thể linh hoạt đáp ứng các tình huống khác nhau.",
      techText1: "Quy trình hỗ trợ kỹ thuật của UNC tuân theo nguyên tắc \"phản hồi nhanh, xử lý chuyên nghiệp, theo dõi toàn diện.\" Với nền tảng ngành sâu và kinh nghiệm kỹ thuật phong phú, UNC cam kết cung cấp dịch vụ hỗ trợ kỹ thuật hiệu quả và chính xác.",
      techServicesTitle: "Dịch vụ hỗ trợ kỹ thuật",
      afterSalesText: "Đội ngũ dịch vụ hậu mãi UNC gồm các kỹ sư giàu kinh nghiệm, có thể phản hồi nhanh chóng các nhu cầu của khách hàng.",
      title: "Hỗ trợ kỹ thuật",
      subtitle: "Truy cập tài liệu sản phẩm, tải xuống, đào tạo và hỗ trợ kỹ thuật.",
      directTitle: "Cần hỗ trợ trực tiếp?",
      directText: "Đội ngũ hỗ trợ kỹ thuật luôn sẵn sàng hỗ trợ lắp đặt, vận hành và xử lý sự cố.",
      contactTeam: "Liên hệ đội hỗ trợ",
      callHotline: "Gọi hotline",
      datasheetsTitle: "Datasheet sản phẩm",
      datasheetsDescription: "Tải thông số kỹ thuật và datasheet chi tiết cho các sản phẩm.",
      datasheetsAction: "Xem datasheet",
      manualsTitle: "Hướng dẫn lắp đặt",
      manualsDescription: "Tài liệu hướng dẫn từng bước và sơ đồ đấu nối để lắp đặt an toàn, hiệu quả.",
      manualsAction: "Xem hướng dẫn",
      softwareTitle: "Phần mềm và firmware",
      softwareDescription: "Tải phần mềm giám sát, firmware mới nhất và công cụ cấu hình.",
      softwareAction: "Tải phần mềm",
      videosTitle: "Video hướng dẫn",
      videosDescription: "Xem video lắp đặt, xử lý sự cố và giới thiệu sản phẩm.",
      videosAction: "Xem video",
      faqTitle: "FAQ",
      faqDescription: "Tìm câu trả lời cho các câu hỏi thường gặp về sản phẩm và dịch vụ.",
      faqAction: "Xem FAQ",
      trainingTitle: "Chương trình đào tạo",
      trainingDescription: "Đăng ký các buổi đào tạo trực tuyến và trực tiếp cho kỹ thuật viên, kỹ sư.",
      trainingAction: "Đăng ký ngay",
    },
    footer: {
      contactNow: "Liên hệ ngay",
      name: "Tên",
      telephone: "Điện thoại",
      counseling: "Nội dung tư vấn",
      sending: "Gửi",
      hotline: "Hotline",
    },
  },
  zh: {
    nav: {
      home: "首页",
      products: "产品",
      company: "公司",
      news: "新闻",
      support: "支持",
      contact: "联系",
      aboutUs: "关于我们",
      solutions: "解决方案",
      productsCenter: "产品中心",
      rnd: "研发与制造",
      solutionHousehold: "家庭储能解决方案",
      solutionCommercial: "工商业储能",
      solutionPhotovoltaic: "光伏系统解决方案",
      rndCapabilities: "研发能力",
      batchProduction: "批量生产能力",
      qualityAssurance: "质量保证",
      technicalSupport: "技术支持",
      postSale: "售后服务",
      dataDownload: "资料下载",
    },
    home: {
      heroTitle: "用清洁能源驱动未来",
      heroTitle2: "创新驱动，绿色赋能",
      heroSubtitle2: "为世界提供清洁能源解决方案",
      heroSubtitle: "高效太阳能逆变器和储能系统的领先制造商",
      cta: "探索产品",
      ctaSecondary: "联系我们",
      globalDesign: "全球设计",
      powerConverterLeader: "成为电力电子变换器领导者",
      solutionsTitle: "解决方案",
      solutionsSubtitle: "多种工作模式可灵活应对不同场景。",
      householdSolutionTitle: "家庭储能解决方案",
      householdSolutionDescription:
        "我们提供高功率密度、高转换效率、可靠保护、智能稳定的混合逆变器和家用电池，适用于家庭节能、别墅供电、阳台光伏和离网场景。",
      commercialSolutionTitle: "工商业储能",
      commercialSolutionDescription: "我们提供多种功率规格的模块化储能变流器、工商业储能系统及EMS综合解决方案，全面满足辅助服务、削峰填谷、需求侧响应、动态扩容等业务需求。",
      photovoltaicSolutionTitle: "光伏系统解决方案",
      photovoltaicSolutionDescription: "我们提供10至110kW全系列光伏逆变器产品，具备高效率、智能稳定和安全可靠的特点，广泛适用于户用、分布式及大型地面光伏电站等众多场景。",
      rndTitle: "研发与制造",
      rndSubtitle: "研发创新，锻造电力未来",
      rndParagraph1: "我们始终将质量视为生存和发展的核心。",
      rndParagraph2: "已通过 ISO 9001 国际质量管理体系认证。",
      rndParagraph3: "拥有包括 ISO 14001 环境管理体系在内的多项国际认证。",
      corporateNews: "企业新闻",
      recommendedProducts: "推荐产品",
      recommendedSubtitle: "安全、可靠、高效，一站式能源解决方案",
    },
    products: {
      title: "产品",
      subtitle: "适用于各种太阳能应用的创新解决方案",
      viewDetails: "查看详情",
      allCategories: "所有类别",
      allProducts: "所有产品",
      loading: "正在加载产品...",
      noProducts: "该类别暂无产品。",
      detailNotFound: "未找到产品",
      backToProducts: "返回产品",
      productImage: "产品图片",
      keyFeatures: "核心特点",
      requestQuote: "获取报价",
      downloadDatasheet: "下载数据表",
      pvInverters: "光伏系统",
      energyStorage: "工商业储能",
      hybridInverters: "家庭储能",
      parameter: "参数",
      manual: "手册",
      positionPrefix: "当前位置：首页 > 产品中心 > ",
      productAdvantages: "产品优势",
      technicalSpecifications: "技术规格",
      productModel: "产品型号",
      specificationsData: "规格数据",
      recommendedProducts: "推荐产品",
      more: "更多",
    },
    company: {
      title: "关于我们",
      subtitle: "15年以上可再生能源创新",
      heroTitle: "关于 UNC Technology",
      heroSubtitle: "UNC —— 绿色能源新动力",
      storyTitle: "公司介绍",
      introP1: "青岛Uni-Convtor技术有限公司（UNC）成立于2021年，深耕可再生能源行业，专注于电源转换技术的研发与应用。",
      introP2: "产品涵盖家用混合逆变器、光伏逆变器及储能PCS，广受国内外市场信赖。",
      introP3: "UNC已建成面积超10,000平方米的智能工厂，年产能可达40万台套。",
      introP4: "UNC致力于成为全球电力电子变换器领域的领军企业。",
      cultureTitle: "企业文化",
      partnerCta: "成为合作伙伴",
      journeyTitle: "发展里程碑",
      certificationsTitle: "荣誉",
      certificationsSubtitle: "国际质量与产品认证",
      milestone2021: "青岛Uni-Convtor技术有限公司成立。",
      milestone2022: "核心研发与制造团队在电力转换领域扩展。",
      milestone2023: "家用混合逆变器和储能产品进入批量生产。",
      milestone2024: "全球产品组合扩展至家用、工商业和光伏系统。",
      milestone2025: "UNC持续推进国际认证和全球市场开拓。",
    },
    contact: {
      title: "联系我们",
      subtitle: "联系我们的团队",
      name: "姓名",
      email: "电子邮件",
      phone: "电话",
      subject: "主题",
      message: "信息",
      send: "提交",
      interesting: "感兴趣的产品",
      company: "公司",
      address: "地址",
      verify: "验证",
      clickVerify: "点击验证",
      heroSubtitle: "联系我们的销售和技术团队，获取适合您的解决方案。",
      information: "联系信息",
      businessHours: "营业时间",
      mondayFriday: "周一至周五",
      saturday: "周六",
      sunday: "周日",
      closed: "休息",
      sendUsMessage: "发送消息",
      success: "您的消息已成功发送！我们将在24小时内回复。",
      error: "消息发送失败，请稍后重试。",
      sending: "发送中...",
      namePlaceholder: "张三",
      emailPlaceholder: "name@company.com",
      subjectPlaceholder: "产品咨询",
      messagePlaceholder: "请告诉我们您的项目需求...",
    },
    common: {
      learnMore: "了解更多",
      readMore: "阅读更多",
      download: "下载",
      loading: "加载中...",
      more: "更多",
      new: "新品",
      selectLanguage: "选择语言",
      toggleMenu: "打开菜单",
    },
    news: {
      title: "新闻与动态",
      subtitle: "了解最新产品发布、认证和行业洞察。",
      noArticles: "暂无新闻文章。",
      productLaunch: "产品发布",
      certification: "认证",
      industryNews: "行业新闻",
      partnership: "合作伙伴",
      events: "活动",
    },
    newsData: {
      "news-483": {
        title: "用UNC Technology的储能光伏一体机释放能源独立！",
        excerpt: "UNC Technology推出了集成式光伏和电池系统，为您实现住宅清洁能源独立。",
        content: "UNC Technology的光伏储能一体机旨在简化家庭清洁能源的部署。该系统集成了光伏发电、储能和智能控制，帮助客户提高自发自用率并保证连续供电。"
      },
      "news-480": {
        title: "UNC在2025年SNEC光伏大会上发布能源解决方案",
        excerpt: "UNC在2025年SNEC光伏展会上展示了家用、商用及光伏能源解决方案。",
        content: "在2025年SNEC光伏大会上，UNC向全球合作伙伴和客户展示了其混合逆变器、储能系列和光伏逆变器产品组合。"
      },
      "solar-inverter-74": {
        title: "混合太阳能逆变器的技术特点",
        excerpt: "混合太阳能逆变器将光伏发电、电池储能和电网交互集成在一个系统中。",
        content: "混合太阳能逆变器支持光伏转换、电池充放电、备份输出和智能能源调度。这些特性使其适用于家庭和商业清洁能源场景。"
      },
      "central-pv-inverter-73": {
        title: "集中式光伏逆变器的优缺点",
        excerpt: "集中式光伏逆变器支持大功率转换，具有集中运维的优势。",
        content: "集中式光伏逆变器通常用于大型电站中进行集中转换以简化运维。系统设计还需考虑冗余、维护及系统级可靠性。"
      },
      "off-grid-hybrid-inverter-72": {
        title: "离网全桥混合逆变器的应用场景是什么？",
        excerpt: "离网混合逆变器适用于偏远地区、备用电源和实现能源独立的场景。",
        content: "离网混合逆变器能够结合光伏发电、储能电池和发电机，为偏远岛屿、别墅以及缺乏市电的区域提供稳定的电力储备。"
      },
      "energy-storage-system-71": {
        title: "户用储能系统的功能与作用",
        excerpt: "户用储能系统可提高自用电率、备用能力及能源管理。",
        content: "户用储能系统存储过剩的光伏电力并在需要时提供电能。它们可以减少对电网的依赖，支持关键负载，并提高家庭能源保障。"
      },
      "solar-storage-companies-70": {
        title: "光储企业的商业模式与技术方向",
        excerpt: "光储企业将储能产品与系统级服务能力相结合。",
        content: "光储企业不断完善住宅和商业应用中的综合产品、智能监控以及面向服务的能源解决方案。"
      },
      "solar-charge-inverter-69": {
        title: "太阳能逆变器有哪些不同类型？",
        excerpt: "太阳能充电逆变器因拓扑结构、功率范围和电网交换模式而异。",
        content: "它们可支持离网、混合甚至并网场景，帮助用户适应不同的使用需求。"
      },
      "pv-panel-inverter-68": {
        title: "光伏逆变器的类型与特点",
        excerpt: "光伏逆变器为光伏发电提供高效转换与监控功能。",
        content: "光伏逆变器的选择需根据应用规模、MPPT范围、防护等级及电站运行需求综合判定。"
      }
    },
    rnd: {
      pageTitle: "\u7814\u53d1\u4e0e\u5236\u9020",
      pageSubtitle: "\u59cb\u7ec8\u5c06\u8d28\u91cf\u89c6\u4e3a\u751f\u5b58\u548c\u53d1\u5c55\u7684\u6838\u5fc3\u3002",
      researchSubtitle: "UNC\u7814\u53d1\u56e2\u961f\u753130\u4f59\u540d\u8d44\u6df1\u4e13\u5bb6\u7ec4\u6210",
      researchText: "UNC\u7814\u53d1\u56e2\u961f\u6db5\u76d6\u8f6f\u4ef6\u3001\u786c\u4ef6\u3001\u7b97\u6cd5\u3001\u7ed3\u6784\u548c\u7535\u6c14\u8bbe\u8ba1\uff0c\u6210\u529f\u5f00\u53d1\u4e86\u50a8\u80fd\u53d8\u6d41\u5668\u548c\u5149\u4f0f\u9006\u53d8\u5668\u3002",
      doctoralDegree: "\u535a\u58eb\u5b66\u4f4d",
      masterDegree: "\u7855\u58eb\u5b66\u4f4d",
      patent: "\u4e13\u5229",
      industryExperience: "\u7535\u529b\u7535\u5b50\u884c\u4e1a\u7ecf\u9a8c",
      standard: "\u6807\u51c6",
      produceSubtitle: "\u5148\u8fdb\u7684\u751f\u4ea7\u8bbe\u65bd\u6709\u6548\u652f\u6491\u548c\u4fdd\u969c\u5236\u9020\u80fd\u529b\u3002",
      produceText: "UNC\u62e5\u6709\u50a8\u80fd\u4ea7\u54c1\u3001\u5bb6\u7528\u6df7\u5408\u9006\u53d8\u5668\u53ca\u81ea\u7814\u7684PCS\u3001BMS\u3001EMS\u7684\u72ec\u7acb\u96c6\u6210\u88c5\u914d\u751f\u4ea7\u7ebf\u3002",
      labArea: "\u5b9e\u9a8c\u5ba4\u9762\u79ef\u8d85\u8fc7400\u5e73\u65b9\u7c73",
      hybridDev: "30kW\u53ca\u4ee5\u4e0b\u6df7\u5408\u9006\u53d8\u5668\u4ea7\u54c1\u7814\u53d1",
      pcsDev: "630kW\u53ca\u4ee5\u4e0bPCS\u4ea7\u54c1\u7814\u53d1",
      pvDev: "110kW\u53ca\u4ee5\u4e0b\u89c4\u683c\u4ea7\u54c1\u7814\u53d1",
      workshopAlt: "UNC\u751f\u4ea7\u8f66\u95f4",
      qualitySubtitle: "UNC\u5df2\u83b7\u5f97ISO9001\u548cISO14001\u8ba4\u8bc1\u3002",
      qualityText: "\u8d28\u91cf\u662f\u516c\u53f8\u751f\u5b58\u548c\u53ef\u6301\u7eed\u53d1\u5c55\u7684\u6838\u5fc3\u3002UNC\u5df2\u5efa\u7acb\u4e25\u683c\u9ad8\u6548\u7684\u8d28\u91cf\u7ba1\u7406\u4f53\u7cfb\u3002",
      qualityRD: "\u7814\u53d1\u4fdd\u969c",
      qualityRDText: "\u62e5\u671010\u5e74\u4ee5\u4e0a\u73b0\u573a\u7ecf\u9a8c\u7684\u8d44\u6df1\u7535\u5b50\u5de5\u7a0b\u5e08\u9886\u5bfc\u7814\u53d1\u56e2\u961f\u3002",
      qualityAfterSale: "\u552e\u540e\u670d\u52a1",
      qualityAfterSaleText: "\u5b8c\u5584\u7684\u552e\u540e\u670d\u52a1\u4f53\u7cfb\u6db5\u76d6\u6280\u672f\u652f\u6301\u3001\u7ef4\u4fee\u670d\u52a1\u548c\u5907\u4ef6\u4f9b\u5e94\u3002",
      qualityInspection: "\u8d28\u91cf\u68c0\u9a8c",
      qualityInspectionText: "\u4e25\u683c\u7684\u8d28\u91cf\u7ba1\u7406\u76d1\u63a7\u539f\u6750\u6599\u91c7\u8d2d\u3001\u751f\u4ea7\u8fc7\u7a0b\u63a7\u5236\u548c\u7ec8\u54c1\u68c0\u9a8c\u3002",
      qualityProduction: "\u751f\u4ea7\u8d28\u91cf\u63a7\u5236",
      qualityProductionText: "\u667a\u80fd\u5316\u8f66\u95f4\u91c7\u7528\u5148\u8fdb\u751f\u4ea7\u8bbe\u65bd\u548c\u5de5\u827a\uff0c\u786e\u4fdd\u8d28\u91cf\u7a33\u5b9a\u3002",
    },
    support: {
      pageTitle: "\u6280\u672f\u652f\u6301",
      pageSubtitle: "\u591a\u79cd\u5de5\u4f5c\u6a21\u5f0f\uff0c\u7075\u6d3b\u5e94\u5bf9\u5404\u79cd\u573a\u666f\u3002",
      techText1: "UNC\u6280\u672f\u652f\u6301\u6d41\u7a0b\u9075\u5faa\u201c\u5feb\u901f\u54cd\u5e94\u3001\u4e13\u4e1a\u5904\u7406\u3001\u5168\u7a0b\u8ddf\u8e2a\u201d\u7684\u539f\u5219\uff0c\u51ed\u5c61\u6df1\u539a\u7684\u884c\u4e1a\u80cc\u666f\u548c\u4e30\u5bcc\u7684\u6280\u672f\u7ecf\u9a8c\uff0cUNC\u81f4\u529b\u4e3a\u5ba2\u6237\u63d0\u4f9b\u9ad8\u6548\u3001\u7cbe\u51c6\u7684\u6280\u672f\u652f\u6301\u670d\u52a1\u3002",
      techServicesTitle: "\u6280\u672f\u652f\u6301\u670d\u52a1",
      afterSalesText: "UNC\u552e\u540e\u670d\u52a1\u56e2\u961f\u7531\u7ecf\u9a8c\u4e30\u5bcc\u3001\u6280\u672f\u7cbe\u6e5b\u7684\u5de5\u7a0b\u5e08\u7ec4\u6210\uff0c\u80fd\u591f\u8fc5\u901f\u54cd\u5e94\u5ba2\u6237\u9700\u6c42\u3002",
      title: "\u6280\u672f\u652f\u6301",
      subtitle: "\u83b7\u53d6\u4ea7\u54c1\u6587\u6863\u3001\u4e0b\u8f7d\u8d44\u6e90\u3001\u57f9\u8bad\u548c\u4e13\u5bb6\u6280\u672f\u652f\u6301\u3002",
      directTitle: "\u9700\u8981\u76f4\u63a5\u652f\u6301\uff1f",
      directText: "\u6211\u4eec\u7684\u6280\u672f\u652f\u6301\u56e2\u961f\u53ef\u534f\u52a9\u60a8\u5b8c\u6210\u5b89\u88c5\u3001\u8c03\u8bd5\u548c\u6545\u969c\u6392\u67e5\u3002",
      contactTeam: "\u8054\u7cfb\u652f\u6301\u56e2\u961f",
      callHotline: "\u62e8\u6253\u70ed\u7ebf",
      datasheetsTitle: "\u4ea7\u54c1\u6570\u636e\u8868",
      datasheetsDescription: "\u4e0b\u8f7d\u6240\u6709\u9006\u53d8\u5668\u548c\u50a8\u80fd\u4ea7\u54c1\u7684\u8be6\u7ec6\u6280\u672f\u89c4\u683c\u4e0e\u6570\u636e\u8868\u3002",
      datasheetsAction: "\u6d4f\u89c8\u6570\u636e\u8868",
      manualsTitle: "\u5b89\u88c5\u624b\u518c",
      manualsDescription: "\u5b89\u5168\u9ad8\u6548\u5b89\u88c5\u6240\u9700\u7684\u5206\u6b65\u6307\u5357\u548c\u63a5\u7ebf\u56fe\u3002",
      manualsAction: "\u67e5\u770b\u624b\u518c",
      softwareTitle: "\u8f6f\u4ef6\u4e0e\u56fa\u4ef6",
      softwareDescription: "\u4e0b\u8f7d\u6700\u65b0\u76d1\u63a7\u8f6f\u4ef6\u3001\u56fa\u4ef6\u66f4\u65b0\u548c\u914d\u7f6e\u5de5\u5177\u3002",
      softwareAction: "\u4e0b\u8f7d\u8f6f\u4ef6",
      videosTitle: "\u89c6\u9891\u6559\u7a0b",
      videosDescription: "\u89c2\u770b\u5b89\u88c5\u3001\u6545\u969c\u6392\u67e5\u548c\u4ea7\u54c1\u6f14\u793a\u89c6\u9891\u3002",
      videosAction: "\u89c2\u770b\u89c6\u9891",
      faqTitle: "\u5e38\u89c1\u95ee\u9898",
      faqDescription: "\u67e5\u627e\u5173\u4e8e\u4ea7\u54c1\u548c\u670d\u52a1\u7684\u5e38\u89c1\u95ee\u9898\u7b54\u6848\u3002",
      faqAction: "\u67e5\u770b FAQ",
      trainingTitle: "\u57f9\u8bad\u9879\u76ee",
      trainingDescription: "\u62a5\u540d\u9762\u5411\u5b89\u88c5\u4eba\u5458\u548c\u5de5\u7a0b\u5e08\u7684\u7ebf\u4e0a\u53ca\u7ebf\u4e0b\u6280\u672f\u57f9\u8bad\u3002",
      trainingAction: "\u7acb\u5373\u62a5\u540d",
    },
    footer: {
      contactNow: "\u7acb\u5373\u8054\u7cfb",
      name: "\u59d3\u540d",
      telephone: "\u7535\u8bdd",
      counseling: "\u548b\u8be2\u5185\u5bb9",
      sending: "\u53d1\u9001",
      hotline: "\u70ed\u7ebf",
    },
  },
  de: {
    nav: {
      home: "Startseite",
      products: "Produkte",
      company: "Unternehmen",
      news: "Nachrichten",
      support: "Support",
      contact: "Kontakt",
      aboutUs: "Ueber uns",
      solutions: "Loesungen",
      productsCenter: "Produktzentrum",
      rnd: "F&E und Fertigung",
      solutionHousehold: "Energiespeicherloesungen fuer Haushalte",
      solutionCommercial: "Gewerbliche und industrielle Energiespeicherung",
      solutionPhotovoltaic: "Photovoltaik-Systemloesungen",
      rndCapabilities: "F&E-Faehigkeiten",
      batchProduction: "Serienproduktionsfaehigkeiten",
      qualityAssurance: "Qualitaetssicherung",
      technicalSupport: "Technischer Support",
      postSale: "After-Sales-Service",
      dataDownload: "Daten-Download",
    },
    home: {
      heroTitle: "Die Zukunft mit sauberer Energie antreiben",
      heroTitle2: "Innovationsgetriebenes grünes Empowerment",
      heroSubtitle2: "Saubere Energielösungen für die Welt bereitstellen",
      heroSubtitle:
        "Fuehrender Hersteller von Solarwechselrichtern und Energiespeichersystemen",
      cta: "Produkte entdecken",
      ctaSecondary: "Kontakt",
      globalDesign: "Globales Design",
      powerConverterLeader: "Fuehrend bei Leistungselektronik-Wandlern werden",
      solutionsTitle: "Loesungen",
      solutionsSubtitle: "Mehrere Betriebsmodi reagieren flexibel auf unterschiedliche Szenarien.",
      householdSolutionTitle: "Energiespeicherloesungen fuer Haushalte",
      householdSolutionDescription:
        "Wir bieten Hybridwechselrichter und Haushaltsbatterien mit hoher Leistungsdichte, hoher Effizienz, zuverlaessigem Schutz, Intelligenz und Stabilitaet fuer verschiedene Heim- und Off-Grid-Anwendungen.",
      commercialSolutionTitle: "Gewerbliche und industrielle Energiespeicherung",
      commercialSolutionDescription: "Wir bieten modulare Energiespeicherumwandler mit verschiedenen Leistungsspezifikationen, gewerbliche und industrielle Speichersysteme sowie EMS-Komplettloesungen, um Anforderungen wie Systemdienstleistungen, Spitzenlastkappung, Laststeuerung und dynamische Kapazitaetserweiterung zu erfuellen.",
      photovoltaicSolutionTitle: "Photovoltaik-Systemloesungen",
      photovoltaicSolutionDescription: "Wir bieten PV-Wechselrichter von 10 bis 110 kW an, die sich durch hohe Effizienz, intelligente Stabilitaet und zuverlaessige Sicherheit auszeichnen und fuer verschiedene Szenarien geeignet sind: von privaten ueber dezentrale bis hin zu grossen Photovoltaik-Freiflaechenanlagen.",
      rndTitle: "F&E und Fertigung",
      rndSubtitle: "Forschung und Innovation fuer die Zukunft der Energie",
      rndParagraph1: "Qualitaet ist fuer uns die Grundlage fuer Bestand und Wachstum.",
      rndParagraph2: "Wir haben die internationale ISO 9001 Qualitaetsmanagement-Zertifizierung erhalten.",
      rndParagraph3: "Wir halten mehrere internationale Zertifizierungen, darunter ISO 14001.",
      corporateNews: "Unternehmensnachrichten",
      recommendedProducts: "Empfohlene Produkte",
      recommendedSubtitle: "Sicher, zuverlaessig, effizient, eine umfassende Energieloesung",
    },
    products: {
      title: "Produkte",
      subtitle: "Innovative Loesungen fuer jede Solaranwendung",
      viewDetails: "Details ansehen",
      allCategories: "Alle Kategorien",
      allProducts: "Alle Produkte",
      loading: "Produkte werden geladen...",
      noProducts: "Keine Produkte in dieser Kategorie gefunden.",
      detailNotFound: "Produkt nicht gefunden",
      backToProducts: "Zurueck zu Produkten",
      productImage: "Produktbild",
      keyFeatures: "Hauptmerkmale",
      requestQuote: "Angebot anfordern",
      downloadDatasheet: "Datenblatt herunterladen",
      pvInverters: "Photovoltaik-System",
      energyStorage: "Gewerbliche und industrielle Energiespeicherung",
      hybridInverters: "Energiespeicher fuer Haushalte",
      parameter: "Parameter",
      manual: "Handbuch",
      positionPrefix: "Position: Startseite > Produktzentrum > ",
      productAdvantages: "Produktvorteile",
      technicalSpecifications: "Technische Spezifikationen",
      productModel: "Produktmodell",
      specificationsData: "Spezifikationsdaten",
      recommendedProducts: "Empfohlene Produkte",
      more: "MEHR",
    },
    company: {
      title: "Ueber uns",
      subtitle: "15+ Jahre Innovation in erneuerbarer Energie",
      heroTitle: "Ueber UNC Technology",
      heroSubtitle: "UNC - Neue treibende Kraft fuer gruene Energie",
      storyTitle: "Unternehmensvorstellung",
      introP1: "Die Qingdao Uni-Convtor Technology Co., Ltd (UNC), gegruendet 2021, ist in der Branche erneuerbare Energien taetig und fokussiert auf F&E und Anwendung von Stromumwandlungstechnologie.",
      introP2: "Das Produktsortiment umfasst Hybrid-Wechselrichter fuer Haushalte, PV-Wechselrichter und Energiespeicher-PCS.",
      introP3: "UNC hat eine intelligente Fabrik mit mehr als 10.000 Quadratmetern gebaut. Die jaehrliche Produktionskapazitaet betraegt bis zu 400.000 Einheiten.",
      introP4: "UNC ist bestrebt, ein fuehrendes Unternehmen fuer globale Leistungselektronik-Konverter zu werden.",
      cultureTitle: "Unternehmenskultur",
      partnerCta: "Partner werden",
      journeyTitle: "Meilensteine",
      certificationsTitle: "Ehrungen",
      certificationsSubtitle: "Internationale Qualitaets- und Produktzertifizierungen",
      milestone2021: "Qingdao Uni-Convtor Technology Co., Ltd wurde gegruendet.",
      milestone2022: "Kern-F&E- und Fertigungsteam in Stromumwandlungsbereichen erweitert.",
      milestone2023: "Haushalts-Hybrid-Wechselrichter und Energiespeicherprodukte gingen in Serienproduktion.",
      milestone2024: "Globales Produktportfolio auf Haushalts-, Gewerbe- und Photovoltaiksysteme ausgeweitet.",
      milestone2025: "UNC setzte internationale Zertifizierung und globale Marktentwicklung fort.",
    },
    contact: {
      title: "Kontakt",
      subtitle: "Kontaktieren Sie unser Team",
      name: "Vollstaendiger Name",
      email: "E-Mail-Adresse",
      phone: "Telefonnummer",
      subject: "Betreff",
      message: "Nachricht",
      send: "Abschicken",
      interesting: "Interessantes Produkt",
      company: "Unternehmen",
      address: "Adresse",
      verify: "Verifizieren",
      clickVerify: "Zum Verifizieren klicken",
      heroSubtitle: "Kontaktieren Sie unser Vertriebs- und Technikteam fuer die passende Loesung.",
      information: "Kontaktinformationen",
      businessHours: "Geschaeftszeiten",
      mondayFriday: "Montag - Freitag",
      saturday: "Samstag",
      sunday: "Sonntag",
      closed: "Geschlossen",
      sendUsMessage: "Senden Sie uns eine Nachricht",
      success: "Ihre Nachricht wurde erfolgreich gesendet. Wir melden uns innerhalb von 24 Stunden.",
      error: "Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es spaeter erneut.",
      sending: "Wird gesendet...",
      namePlaceholder: "Max Mustermann",
      emailPlaceholder: "max@firma.com",
      subjectPlaceholder: "Produktanfrage",
      messagePlaceholder: "Beschreiben Sie Ihre Projektanforderungen...",
    },
    common: {
      learnMore: "Mehr erfahren",
      readMore: "Weiterlesen",
      download: "Herunterladen",
      loading: "Wird geladen...",
      more: "Mehr",
      new: "NEU",
      selectLanguage: "Sprache auswaehlen",
      toggleMenu: "Menue oeffnen",
    },
    news: {
      title: "Nachrichten und Updates",
      subtitle: "Aktuelle Produktstarts, Zertifizierungen und Brancheneinblicke.",
      noArticles: "Keine Nachrichten verfuegbar.",
      productLaunch: "Produktstart",
      certification: "Zertifizierung",
      industryNews: "Branchennachrichten",
      partnership: "Partnerschaft",
      events: "Veranstaltungen",
    },
    newsData: {
      "news-483": {
        title: "Entfesseln Sie Ihre Energieunabhängigkeit mit dem All-In-One PV- & Batteriesystem von UNC Technology!",
        excerpt: "UNC Technology präsentiert ein integriertes Photovoltaik- und Batteriesystem für die Unabhängigkeit bei sauberer Wohnenergie.",
        content: "Das All-in-One-Photovoltaik- und Batteriesystem von UNC Technology wurde entwickelt, um den Einsatz von sauberer Energie im Haushalt zu vereinfachen. Das System kombiniert PV-Erzeugung, Speicherung und intelligente Steuerung, um Kunden zu helfen, den Eigenverbrauch zu verbessern und die Kontinuität der Stromversorgung sicherzustellen."
      },
      "news-480": {
        title: "UNC präsentiert Energielösungen auf der SNEC PV Power Expo 2025",
        excerpt: "UNC präsentierte auf der SNEC PV Power Expo 2025 Energielösungen für Haushalte, Gewerbe und Photovoltaikanlagen.",
        content: "Auf der SNEC PV Power Expo 2025 demonstrierte UNC sein Portfolio an Hybrid-Wechselrichtern, Energiespeichern und Photovoltaik-Wechselrichtern für globale Partner."
      },
      "solar-inverter-74": {
        title: "Technische Eigenschaften von hybriden Solar-Wechselrichtern",
        excerpt: "Hybride Solar-Wechselrichter integrieren PV-Erzeugung, Batteriespeicherung und Netzinteraktion in einem System.",
        content: "Hybride Solar-Wechselrichter unterstützen PV-Umwandlung, Batterieladung/-entladung und intelligente Energieplanung. Sie eignen sich für private und gewerbliche Reinenergie-Szenarien."
      },
      "central-pv-inverter-73": {
        title: "Vor- und Nachteile von Zentralen PV-Wechselrichtern",
        excerpt: "Zentrale PV-Wechselrichter unterstützen große Leistungsumwandlung mit zentralem Betrieb und Wartung.",
        content: "Zentrale PV-Wechselrichter werden häufig in großen Kraftwerken eingesetzt, in denen eine zentrale Umwandlung den Betrieb vereinfacht."
      },
      "off-grid-hybrid-inverter-72": {
        title: "Was sind die Einsatzszenarien für Off-Grid-Hybrid-Wechselrichter?",
        excerpt: "Off-Grid-Hybrid-Wechselrichter eignen sich für abgelegene Standorte, Notstrom und Energieautarkie.",
        content: "Netzunabhängige Hybrid-Wechselrichter können PV-Erzeugung, Akkus und Generatoren kombinieren, um abgelegene Orte zu versorgen."
      },
      "energy-storage-system-71": {
        title: "Funktionen und Rollen privater Energiespeichersysteme",
        excerpt: "Private Energiespeichersysteme verbessern den Eigenverbrauch und die Energieverwaltung.",
        content: "Sie speichern überschüssigen PV-Strom und geben ihn bei Bedarf ab, reduzieren Netzabhängigkeit und unterstützen kritische Lasten."
      },
      "solar-storage-companies-70": {
        title: "Geschäftsmodell und technologische Richtung von Solar- und Speicherunternehmen",
        excerpt: "Sie kombinieren Energiespeicherprodukte mit Servicefähigkeiten auf Systemebene.",
        content: "Lösungsanbieter verfeinern integrierte Produkte, intelligentes Monitoring und dienstleistungsorientierte Energielösungen."
      },
      "solar-charge-inverter-69": {
        title: "Welche verschiedenen Arten von Solar-Lade-Wechselrichtern gibt es?",
        excerpt: "Sie variieren je nach Topologie, Leistungsbereich und Netzinteraktionsmodi.",
        content: "Solar-Lade-Wechselrichter unterstützen netzferne, hybride und netzgekoppelte Szenarien für verschiedenste Nutzer."
      },
      "pv-panel-inverter-68": {
        title: "Arten und Eigenschaften von PV-Panel-Wechselrichtern",
        excerpt: "Sie bieten effiziente Umwandlung und Überwachung für Photovoltaik.",
        content: "Die Wahl hängt von Anlagengröße, MPPT-Bereich, Schutzart und Anforderungsbedingungen ab."
      }
    },
    rnd: {
      pageTitle: "F&E und Fertigung",
      pageSubtitle: "Qualitaet ist fuer uns die Grundlage fuer Bestand und Wachstum.",
      researchSubtitle: "Das UNC-F&E-Team besteht aus mehr als 30 erfahrenen Experten",
      researchText: "Das UNC-F&E-Team deckt Software, Hardware, Algorithmen, Struktur und Elektrodesign ab.",
      doctoralDegree: "Doktortitel",
      masterDegree: "Mastertitel",
      patent: "Patent",
      industryExperience: "Erfahrung in der Leistungselektronik",
      standard: "Standard",
      produceSubtitle: "Moderne Produktionsanlagen unterstuetzen die Fertigungskapazitaet effizient.",
      produceText: "UNC verfuegt ueber eigenstaendige integrierte Montagelinien fuer Energiespeicherprodukte und Hybridwechselrichter.",
      labArea: "Laborflaeche ueber 400 Quadratmeter",
      hybridDev: "Entwicklung von Hybridwechselrichter-Produkten bis 30 kW",
      pcsDev: "Entwicklung von PCS-Produkten bis 630 kW",
      pvDev: "Entwicklung von Produkten bis 110 kW",
      workshopAlt: "UNC-Produktionswerkstatt",
      qualitySubtitle: "UNC hat ISO9001- und ISO14001-Zertifizierungen erhalten.",
      qualityText: "Qualitaet ist der Kern fuer Bestand und nachhaltige Entwicklung des Unternehmens.",
      qualityRD: "F&E-Sicherheit",
      qualityRDText: "Erfahrene Elektronikingenieure mit mehr als 10 Jahren Praxiserfahrung leiten das F&E-Team.",
      qualityAfterSale: "After-Sales-Service",
      qualityAfterSaleText: "Ein umfassendes After-Sales-System umfasst technischen Support, Reparaturservice und Ersatzteilversorgung.",
      qualityInspection: "Qualitaetspruefung",
      qualityInspectionText: "Strenge Qualitaetskontrolle ueberwacht Rohstoffeinkauf, Produktionsprozess und Endpruefung.",
      qualityProduction: "Produktionsqualitaetskontrolle",
      qualityProductionText: "Die intelligente Werkstatt nutzt moderne Produktionsanlagen fuer stabile Qualitaet.",
    },
    support: {
      pageTitle: "Technischer Support",
      pageSubtitle: "Mehrere Arbeitsmodi reagieren flexibel auf verschiedene Szenarien.",
      techText1: "Der technische Support-Prozess von UNC folgt den Grundsaetzen schnelle Reaktion, professionelle Abwicklung und vollstaendiges Tracking.",
      techServicesTitle: "Technische Support-Services",
      afterSalesText: "Das After-Sales-Team von UNC besteht aus erfahrenen und hochqualifizierten Ingenieuren, die schnell auf Kundenwuensche reagieren koennen.",
      title: "Technischer Support",
      subtitle: "Produktdokumentation, Downloads, Schulungen und technische Hilfe.",
      directTitle: "Direkte Unterstuetzung benoetigt?",
      directText: "Unser Technikteam hilft bei Installation, Inbetriebnahme und Fehlersuche.",
      contactTeam: "Support-Team kontaktieren",
      callHotline: "Hotline anrufen",
      datasheetsTitle: "Produktdatenblaetter",
      datasheetsDescription: "Detaillierte technische Daten und Datenblaetter fuer alle Produkte herunterladen.",
      datasheetsAction: "Datenblaetter ansehen",
      manualsTitle: "Installationshandbuecher",
      manualsDescription: "Schritt-fuer-Schritt-Anleitungen und Schaltplaene fuer sichere Installation.",
      manualsAction: "Handbuecher ansehen",
      softwareTitle: "Software und Firmware",
      softwareDescription: "Aktuelle Monitoring-Software, Firmware und Konfigurationstools herunterladen.",
      softwareAction: "Software herunterladen",
      videosTitle: "Video-Tutorials",
      videosDescription: "Installations-, Fehlerbehebungs- und Produktvideos ansehen.",
      videosAction: "Videos ansehen",
      faqTitle: "FAQ",
      faqDescription: "Antworten auf haeufige Fragen zu Produkten und Services.",
      faqAction: "FAQ ansehen",
      trainingTitle: "Schulungsprogramme",
      trainingDescription: "Online- und Vor-Ort-Schulungen fuer Installateure und Ingenieure buchen.",
      trainingAction: "Jetzt anmelden",
    },
    footer: {
      contactNow: "Jetzt kontaktieren",
      name: "Name",
      telephone: "Telefon",
      counseling: "Beratung",
      sending: "Senden",
      hotline: "Hotline",
    },
  },
  es: {
    nav: {
      home: "Inicio",
      products: "Productos",
      company: "Empresa",
      news: "Noticias",
      support: "Soporte",
      contact: "Contacto",
      aboutUs: "Sobre nosotros",
      solutions: "Soluciones",
      productsCenter: "Centro de productos",
      rnd: "I+D y fabricacion",
      solutionHousehold: "Soluciones de almacenamiento para el hogar",
      solutionCommercial: "Almacenamiento comercial e industrial",
      solutionPhotovoltaic: "Soluciones de sistemas fotovoltaicos",
      rndCapabilities: "Capacidades de I+D",
      batchProduction: "Capacidades de produccion en serie",
      qualityAssurance: "Aseguramiento de calidad",
      technicalSupport: "Soporte tecnico",
      postSale: "Servicio posventa",
      dataDownload: "Descarga de datos",
    },
    home: {
      heroTitle: "Impulsando el futuro con energia limpia",
      heroSubtitle:
        "Fabricante lider de inversores solares y sistemas de almacenamiento de energia",
      cta: "Explorar productos",
      ctaSecondary: "Contacto",
      globalDesign: "Disposición global",
      powerConverterLeader: "Conviértase en líder en convertidores electrónicos de potencia",
      heroTitle2: "Empoderamiento verde impulsado por la innovación",
      heroSubtitle2: "Proporcionar soluciones de energía limpia para el mundo",
      solutionsTitle: "Soluciones",
      solutionsSubtitle: "Varios modos de trabajo responden con flexibilidad a diferentes escenarios.",
      householdSolutionTitle: "Soluciones de almacenamiento para el hogar",
      householdSolutionDescription:
        "Ofrecemos inversores hibridos y baterias domesticas con alta densidad de potencia, alta eficiencia, proteccion confiable, inteligencia y estabilidad para aplicaciones residenciales y fuera de red.",
      commercialSolutionTitle: "Almacenamiento comercial e industrial",
      commercialSolutionDescription: "Proporcionamos convertidores modulares de almacenamiento de energia con diversas especificaciones de potencia, sistemas de almacenamiento C&I y soluciones integrales EMS para cubrir necesidades de servicios auxiliares, reduccion de picos, respuesta a la demanda y expansion dinamica de capacidad.",
      photovoltaicSolutionTitle: "Soluciones de sistemas fotovoltaicos",
      photovoltaicSolutionDescription: "Ofrecemos inversores fotovoltaicos que van de 10 a 110 kW, destacando por su alta eficiencia, estabilidad inteligente y gran seguridad. Adaptables a diversos entornos, desde sistemas residenciales y distribuidos hasta plantas fotovoltaicas a gran escala.",
      rndTitle: "I+D y fabricacion",
      rndSubtitle: "Investigacion e innovacion para forjar el futuro de la electricidad",
      rndParagraph1: "Siempre consideramos la calidad como el nucleo de la supervivencia y el desarrollo.",
      rndParagraph2: "Hemos obtenido la certificacion internacional ISO 9001 de gestion de calidad.",
      rndParagraph3: "Contamos con multiples certificaciones internacionales, incluida ISO 14001.",
      corporateNews: "Noticias corporativas",
      recommendedProducts: "Productos recomendados",
      recommendedSubtitle: "Seguro, confiable, eficiente, solucion integral de energia",
    },
    products: {
      title: "Productos",
      subtitle: "Soluciones innovadoras para cada aplicacion solar",
      viewDetails: "Ver detalles",
      allCategories: "Todas las categorias",
      allProducts: "Todos los productos",
      loading: "Cargando productos...",
      noProducts: "No se encontraron productos en esta categoria.",
      detailNotFound: "Producto no encontrado",
      backToProducts: "Volver a productos",
      productImage: "Imagen del producto",
      keyFeatures: "Caracteristicas principales",
      requestQuote: "Solicitar cotizacion",
      downloadDatasheet: "Descargar ficha tecnica",
      pvInverters: "Sistema fotovoltaico",
      energyStorage: "Almacenamiento comercial e industrial",
      hybridInverters: "Almacenamiento de energia para el hogar",
      parameter: "Parametro",
      manual: "Manual",
      positionPrefix: "Posicion: Inicio > Centro de productos > ",
      productAdvantages: "Ventajas del producto",
      technicalSpecifications: "Especificaciones tecnicas",
      productModel: "Modelo de producto",
      specificationsData: "Datos de especificaciones",
      recommendedProducts: "Productos recomendados",
      more: "MAS",
    },
    company: {
      title: "Sobre nosotros",
      subtitle: "15+ anos de innovacion en energia renovable",
      heroTitle: "Sobre UNC Technology",
      heroSubtitle: "UNC - Nueva fuerza impulsora de energia verde",
      storyTitle: "Presentacion de la empresa",
      introP1: "Qingdao Uni-Convtor Technology Co., Ltd (UNC), fundada en 2021, se ha dedicado a la industria de energias renovables, centrandose en I+D y aplicacion de tecnologia de conversion de energia.",
      introP2: "La gama de productos incluye inversores hibridos para el hogar, inversores fotovoltaicos y PCS de almacenamiento de energia.",
      introP3: "UNC ha construido una fabrica inteligente de mas de 10.000 metros cuadrados. La capacidad de produccion anual alcanza las 400.000 unidades.",
      introP4: "UNC esta comprometida a convertirse en lider global en convertidores de electronica de potencia.",
      cultureTitle: "Cultura corporativa",
      partnerCta: "Colabore con nosotros",
      journeyTitle: "Hitos",
      certificationsTitle: "Honores",
      certificationsSubtitle: "Certificaciones internacionales de calidad y productos",
      milestone2021: "Qingdao Uni-Convtor Technology Co., Ltd fue fundada.",
      milestone2022: "El equipo central de I+D y fabricacion se expandio en los campos de conversion de energia.",
      milestone2023: "Los inversores hibridos para el hogar y los productos de almacenamiento de energia entraron en produccion en serie.",
      milestone2024: "La cartera de productos globales se expandio a sistemas de hogar, comerciales e industriales y fotovoltaicos.",
      milestone2025: "UNC continuo con la certificacion internacional y el desarrollo del mercado global.",
    },
    contact: {
      title: "Contacto",
      subtitle: "Pongase en contacto con nuestro equipo",
      name: "Nombre completo",
      email: "Correo electronico",
      phone: "Telefono",
      subject: "Asunto",
      message: "Mensaje",
      send: "Enviar",
      interesting: "Producto de interes",
      company: "Empresa",
      address: "Direccion",
      verify: "Verificar",
      clickVerify: "Haga clic para verificar",
      heroSubtitle: "Contacte con nuestro equipo comercial y tecnico para encontrar la solucion adecuada.",
      information: "Informacion de contacto",
      businessHours: "Horario de atencion",
      mondayFriday: "Lunes - Viernes",
      saturday: "Sabado",
      sunday: "Domingo",
      closed: "Cerrado",
      sendUsMessage: "Envienos un mensaje",
      success: "Su mensaje se ha enviado correctamente. Responderemos en 24 horas.",
      error: "No se pudo enviar el mensaje. Intentelo de nuevo mas tarde.",
      sending: "Enviando...",
      namePlaceholder: "Juan Perez",
      emailPlaceholder: "juan@empresa.com",
      subjectPlaceholder: "Consulta de producto",
      messagePlaceholder: "Cuentenos los requisitos de su proyecto...",
    },
    common: {
      learnMore: "Mas informacion",
      readMore: "Leer mas",
      download: "Descargar",
      loading: "Cargando...",
      more: "Mas",
      new: "NUEVO",
      selectLanguage: "Seleccionar idioma",
      toggleMenu: "Abrir menu",
    },
    news: {
      title: "Noticias y actualizaciones",
      subtitle: "Mantengase informado sobre lanzamientos, certificaciones y tendencias del sector.",
      noArticles: "No hay noticias disponibles.",
      productLaunch: "Lanzamiento",
      certification: "Certificacion",
      industryNews: "Noticias del sector",
      partnership: "Alianza",
      events: "Eventos",
    },
    newsData: {
      "news-483": {
        title: "¡Desate la Independencia Energética con el Sistema Integrado PV y Batería de UNC Technology!",
        excerpt: "UNC Technology presenta un sistema integrado fotovoltaico y de batería para la independencia energética limpia residencial.",
        content: "El sistema integrado fotovoltaico y de batería de UNC Technology está diseñado para simplificar el despliegue de energía limpia en el hogar. El sistema combina generación fotovoltaica, almacenamiento y control inteligente para ayudar a los clientes a mejorar el autoconsumo y la continuidad del suministro de energía."
      },
      "news-480": {
        title: "UNC presenta soluciones energéticas en la SNEC PV Power Expo 2025",
        excerpt: "UNC exhibió soluciones de energía residencial, comercial y fotovoltaica en la SNEC Expo 2025.",
        content: "En la SNEC PV Power Expo 2025, UNC demostró su cartera de inversores híbridos, almacenamiento de energía e inversores fotovoltaicos para socios globales."
      },
      "solar-inverter-74": {
        title: "Características técnicas de los inversores solares híbridos",
        excerpt: "Los inversores solares híbridos integran generación fotovoltaica, almacenamiento en baterías e interacción con la red.",
        content: "Los inversores solares híbridos admiten la conversión fotovoltaica, la carga y descarga de baterías y la programación inteligente de energía, ideales para el hogar y el comercio."
      },
      "central-pv-inverter-73": {
        title: "Ventajas y desventajas de los inversores fotovoltaicos centrales",
        excerpt: "Los inversores fotovoltaicos centrales admiten conversión de gran potencia con operación y mantenimiento centralizados.",
        content: "Los inversores fotovoltaicos centrales se suelen utilizar en grandes centrales eléctricas para simplificar la operación."
      },
      "off-grid-hybrid-inverter-72": {
        title: "¿Cuáles son los escenarios de aplicación de los inversores híbridos fuera de la red?",
        excerpt: "Destinados a sitios remotos, energía de respaldo e independencia energética.",
        content: "Combinan generación fotovoltaica, baterías de almacenamiento y soporte de generador para entregar energía estable."
      },
      "energy-storage-system-71": {
        title: "Funciones y roles de los sistemas de almacenamiento residencial",
        excerpt: "Mejoran el autoconsumo, la capacidad de respaldo y la gestión energética.",
        content: "Almacenan excedentes de PV para usarlos más tarde, reduciendo dependencia y cubriendo cargas críticas."
      },
      "solar-storage-companies-70": {
        title: "Modelo de negocio y tecnología de empresas de almacenamiento solar",
        excerpt: "Combinan productos de almacenamiento de energía y servicios integrales.",
        content: "Continúan expandiendo productos integrales, monitoreo inteligente y soluciones orientadas al servicio."
      },
      "solar-charge-inverter-69": {
        title: "¿Cuáles son los diferentes tipos de inversores de carga solar?",
        excerpt: "Varían según topología, rango de potencia e interacción con la red.",
        content: "Admiten uso fuera de la red, híbrido y conectado a esta, para satisfacer a los clientes según el caso fotovoltaico."
      },
      "pv-panel-inverter-68": {
        title: "Tipos y características de los inversores fotovoltaicos",
        excerpt: "Ofrecen conversión eficiente y monitoreo para la generación renovable.",
        content: "La elección del inversor de panel fotovoltaico depende del tamaño, rango MPPT, protección e instalaciones."
      }
    },
    rnd: {
      pageTitle: "I+D y Fabricacion",
      pageSubtitle: "Siempre consideramos la calidad como el nucleo de la supervivencia y el desarrollo.",
      researchSubtitle: "El equipo de I+D de UNC esta formado por mas de 30 expertos senior",
      researchText: "El equipo de I+D de UNC abarca software, hardware, algoritmos, estructura y diseno electrico.",
      doctoralDegree: "Doctorado",
      masterDegree: "Maestria",
      patent: "Patente",
      industryExperience: "Experiencia en electronica de potencia",
      standard: "Norma",
      produceSubtitle: "Las instalaciones de produccion avanzadas apoyan y garantizan la capacidad de fabricacion.",
      produceText: "UNC cuenta con lineas de ensamblaje integradas independientes para productos de almacenamiento de energia e inversores hibridos.",
      labArea: "Area de laboratorio superior a 400 metros cuadrados",
      hybridDev: "Desarrollo de inversores hibridos de hasta 30 kW",
      pcsDev: "Desarrollo de productos PCS de hasta 630 kW",
      pvDev: "Desarrollo de productos de hasta 110 kW",
      workshopAlt: "Taller de produccion de UNC",
      qualitySubtitle: "UNC ha obtenido las certificaciones ISO9001 e ISO14001.",
      qualityText: "La calidad es el nucleo de la supervivencia y el desarrollo sostenible de la empresa.",
      qualityRD: "Garantia de I+D",
      qualityRDText: "Ingenieros electronicos senior con mas de 10 anos de experiencia lideran el equipo de I+D.",
      qualityAfterSale: "Servicio posventa",
      qualityAfterSaleText: "Un sistema de servicio posventa completo cubre soporte tecnico, servicio de reparacion y suministro de repuestos.",
      qualityInspection: "Inspeccion de calidad",
      qualityInspectionText: "Un estricto control de calidad supervisa la adquisicion de materias primas, el proceso de produccion y la inspeccion del producto final.",
      qualityProduction: "Control de calidad de produccion",
      qualityProductionText: "El taller inteligente utiliza instalaciones y procesos de produccion avanzados para garantizar una calidad estable.",
    },
    support: {
      pageTitle: "Soporte tecnico",
      pageSubtitle: "Con multiples modos de trabajo, UNC Energy Storage puede responder de manera flexible a varios escenarios.",
      techText1: "El proceso de soporte tecnico de UNC sigue los principios de respuesta rapida, manejo profesional y seguimiento completo.",
      techServicesTitle: "Servicios de soporte tecnico",
      afterSalesText: "El equipo de servicio posventa de UNC esta compuesto por ingenieros experimentados y altamente calificados que pueden responder rapidamente a las necesidades del cliente.",
      title: "Soporte tecnico",
      subtitle: "Acceda a documentacion, descargas, capacitacion y soporte tecnico experto.",
      directTitle: "Necesita soporte directo?",
      directText: "Nuestro equipo tecnico puede ayudarle con instalacion, puesta en marcha y solucion de problemas.",
      contactTeam: "Contactar soporte",
      callHotline: "Llamar hotline",
      datasheetsTitle: "Fichas tecnicas",
      datasheetsDescription: "Descargue especificaciones tecnicas y fichas de todos los productos.",
      datasheetsAction: "Ver fichas",
      manualsTitle: "Manuales de instalacion",
      manualsDescription: "Guias paso a paso y diagramas para una instalacion segura y eficiente.",
      manualsAction: "Ver manuales",
      softwareTitle: "Software y firmware",
      softwareDescription: "Descargue software de monitoreo, firmware y herramientas de configuracion.",
      softwareAction: "Descargar software",
      videosTitle: "Video tutoriales",
      videosDescription: "Vea videos de instalacion, solucion de problemas y demostraciones.",
      videosAction: "Ver videos",
      faqTitle: "FAQ",
      faqDescription: "Encuentre respuestas a preguntas frecuentes sobre productos y servicios.",
      faqAction: "Ver FAQ",
      trainingTitle: "Programas de capacitacion",
      trainingDescription: "Registrese en capacitaciones tecnicas online y presenciales.",
      trainingAction: "Registrarse",
    },
    footer: {
      contactNow: "Contactenos ahora",
      name: "Nombre",
      telephone: "Telefono",
      counseling: "Consulta",
      sending: "Enviar",
      hotline: "Hotline",
    },
  },
} as const;

type Locale = keyof typeof translations;
const DEFAULT_LOCALE: Locale = "en";

interface LanguageContextValue {
  locale: Locale;
  t: (key: string) => string;
  switchLanguage: (lang: Locale) => void;
  availableLocales: Locale[];
}

function getNestedTranslation(source: unknown, keys: string[]): string | undefined {
  let value = source;

  for (const key of keys) {
    if (!value || typeof value !== "object" || !(key in value)) {
      return undefined;
    }

    value = (value as Record<string, unknown>)[key];
  }

  return typeof value === "string" ? value : undefined;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(DEFAULT_LOCALE);

  useEffect(() => {
    const savedLocale = window.localStorage.getItem("site-locale");
    if (savedLocale && savedLocale in translations) {
      const timer = window.setTimeout(() => {
        setLocale(savedLocale as Locale);
      }, 0);

      return () => window.clearTimeout(timer);
    }
  }, []);

  const t = useCallback(
    (key: string) => {
      const keys = key.split(".");
      return (
        getNestedTranslation(translations[locale], keys) ||
        getNestedTranslation(translations.en, keys) ||
        key
      );
    },
    [locale]
  );

  const switchLanguage = useCallback((lang: Locale) => {
    if (translations[lang]) {
      setLocale(lang);
      window.localStorage.setItem("site-locale", lang);
    }
  }, []);

  return (
    <LanguageContext.Provider
      value={{
        locale,
        t,
        switchLanguage,
        availableLocales: ["zh", "en", "vi", "de", "es"],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export default LanguageContext;
