"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";

/**
 * Language Context - Quản lý đa ngôn ngữ (ZH/EN/VI/DE/ES)
 */

const translations = {
  en: {
    nav: {
      home: "Home",
      products: "Products",
      company: "Company",
      news: "News",
      support: "Support",
      contact: "Contact Us",
      aboutUs: "About Us",
      solutions: "Solution",
      productsCenter: "Product Center",
      rnd: "R&D and Manufacturing",
      solutionHousehold: "Household Energy Storage Solutions",
      solutionCommercial: "Industrial and Commercial Energy Storage",
      solutionPhotovoltaic: "Photovoltaic System Solutions",
      rndCapabilities: "R&D Capabilities",
      batchProduction: "Batch production capabilities",
      qualityAssurance: "Quality assurance",
      technicalSupport: "Technical Support",
      postSale: "After-sales service",
      dataDownload: "Data download",
    },
    home: {
      heroTitle: "Powering the Future with Clean Energy",
      heroSubtitle:
        "Leading manufacturer of high-efficiency solar inverters and energy storage systems",
      cta: "Explore Products",
      ctaSecondary: "Contact Us",
      globalDesign: "Global Design",
      powerConverterLeader: "Become a leader in power electronic converters",
      solutionsTitle: "Solutions",
      solutionsSubtitle: "Multiple operating modes flexibly respond to different scenarios.",
      householdSolutionTitle: "Household energy storage solutions",
      householdSolutionDescription:
        "We offer hybrid inverters and household batteries with high power density, high conversion efficiency, reliable protection, intelligence, and stability for home energy saving, villa power supply, balcony solar, data centers, and remote islands.",
      commercialSolutionTitle: "Commercial and industrial energy storage",
      photovoltaicSolutionTitle: "Photovoltaic system solutions",
      rndTitle: "R&D and Manufacturing",
      rndSubtitle: "Research and innovation, forging the future of electricity",
      rndParagraph1: "We always regard quality as the core of survival and development.",
      rndParagraph2: "We have passed ISO 9001 international quality management system certification.",
      rndParagraph3: "We hold multiple international certifications, including ISO 14001 environmental management system certification.",
      corporateNews: "Corporate News",
    },
    products: {
      title: "Our Products",
      subtitle: "Innovative solutions for every solar application",
      viewDetails: "View Details",
      allCategories: "All Categories",
      allProducts: "All Products",
      loading: "Loading products...",
      noProducts: "No products found in this category.",
      detailNotFound: "Product Not Found",
      backToProducts: "Back to Products",
      productImage: "Product Image",
      keyFeatures: "Key Features",
      requestQuote: "Request a Quote",
      downloadDatasheet: "Download Datasheet",
      technicalSpecifications: "Technical Specifications",
      pvInverters: "Photovoltaic System",
      energyStorage: "Industrial and Commercial Energy Storage",
      hybridInverters: "Household Energy Storage",
    },
    company: {
      title: "About Us",
      subtitle: "15+ years of innovation in renewable energy",
      heroTitle: "About SolarTech Energy",
      heroSubtitle:
        "15+ years of innovation in renewable energy, delivering world-class solar solutions trusted by partners worldwide.",
      storyTitle: "Our Story",
      storyP1:
        "Founded in 2011, SolarTech Energy has grown from a small R&D team to a leading manufacturer of solar inverters and energy storage systems.",
      storyP2:
        "With over 500 employees, modern manufacturing facilities, and a global presence across 30+ countries, we continue to advance renewable energy technology.",
      partnerCta: "Partner With Us",
      journeyTitle: "Our Journey",
      certificationsTitle: "Certifications & Standards",
      certificationsSubtitle:
        "Our products meet the highest international safety and quality standards.",
      milestone2011: "Company founded in Ho Chi Minh City",
      milestone2014: "First 1 GW of inverters shipped globally",
      milestone2017: "Launched energy storage product line",
      milestone2019: "Achieved TÜV Rheinland certification",
      milestone2022: "Expanded to 30+ countries worldwide",
      milestone2025: "Surpassed 10 GW total global shipments",
    },
    contact: {
      title: "Contact Us",
      subtitle: "Get in touch with our team",
      name: "Full Name",
      email: "Email Address",
      phone: "Phone Number",
      subject: "Subject",
      message: "Message",
      send: "Send Message",
      heroSubtitle:
        "Get in touch with our sales and technical team. We're here to help you find the right solution.",
      information: "Contact Information",
      address: "Address",
      businessHours: "Business Hours",
      mondayFriday: "Monday - Friday",
      saturday: "Saturday",
      sunday: "Sunday",
      closed: "Closed",
      sendUsMessage: "Send Us a Message",
      success:
        "Your message has been sent successfully! We'll get back to you within 24 hours.",
      error: "Failed to send message. Please try again later.",
      sending: "Sending...",
      namePlaceholder: "John Doe",
      emailPlaceholder: "john@company.com",
      subjectPlaceholder: "Product Inquiry",
      messagePlaceholder: "Tell us about your project requirements...",
    },
    common: {
      learnMore: "Learn More",
      readMore: "Read More",
      download: "Download",
      loading: "Loading...",
      more: "More",
      new: "NEW",
      selectLanguage: "Select language",
      toggleMenu: "Toggle menu",
    },
    news: {
      title: "News & Updates",
      subtitle:
        "Stay informed with the latest product launches, certifications, and industry insights.",
      noArticles: "No news articles available.",
      productLaunch: "Product Launch",
      certification: "Certification",
      industryNews: "Industry News",
      partnership: "Partnership",
      events: "Events",
    },
    support: {
      title: "Technical Support",
      subtitle:
        "Access product documentation, downloads, training resources, and expert technical support.",
      directTitle: "Need Direct Support?",
      directText:
        "Our technical support team is available to help you with installation, commissioning, and troubleshooting.",
      contactTeam: "Contact Support Team",
      callHotline: "Call Hotline",
      datasheetsTitle: "Product Datasheets",
      datasheetsDescription:
        "Download detailed technical specifications and datasheets for all our inverter and storage products.",
      datasheetsAction: "Browse Datasheets",
      manualsTitle: "Installation Manuals",
      manualsDescription:
        "Step-by-step installation guides and wiring diagrams for safe and efficient product setup.",
      manualsAction: "View Manuals",
      softwareTitle: "Software & Firmware",
      softwareDescription:
        "Download the latest monitoring software, firmware updates, and configuration tools.",
      softwareAction: "Download Software",
      videosTitle: "Video Tutorials",
      videosDescription:
        "Watch installation walkthroughs, troubleshooting guides, and product demonstration videos.",
      videosAction: "Watch Videos",
      faqTitle: "FAQ",
      faqDescription:
        "Find answers to the most commonly asked questions about our products and services.",
      faqAction: "View FAQ",
      trainingTitle: "Training Programs",
      trainingDescription:
        "Register for online and in-person technical training sessions for installers and engineers.",
      trainingAction: "Register Now",
    },
    footer: {
      contactNow: "Contact Us Now",
      name: "Name",
      telephone: "Telephone",
      counseling: "Counseling",
      sending: "Sending",
      hotline: "Hotline",
    },
  },
  vi: {
    nav: {
      home: "Trang chủ",
      products: "Sản phẩm",
      company: "Công ty",
      news: "Tin tức",
      support: "Hỗ trợ",
      contact: "Liên hệ",
      aboutUs: "Về chúng tôi",
      solutions: "Giải pháp",
      productsCenter: "Trung tâm sản phẩm",
      rnd: "R&D và sản xuất",
      solutionHousehold: "Giải pháp lưu trữ năng lượng gia đình",
      solutionCommercial: "Lưu trữ năng lượng thương mại và công nghiệp",
      solutionPhotovoltaic: "Giải pháp hệ thống quang điện",
      rndCapabilities: "Năng lực R&D",
      batchProduction: "Năng lực sản xuất hàng loạt",
      qualityAssurance: "Đảm bảo chất lượng",
      technicalSupport: "Hỗ trợ kỹ thuật",
      postSale: "Dịch vụ sau bán hàng",
      dataDownload: "Tải dữ liệu",
    },
    home: {
      heroTitle: "Kiến tạo tương lai với năng lượng sạch",
      heroSubtitle:
        "Nhà sản xuất hàng đầu biến tần năng lượng mặt trời và hệ thống lưu trữ năng lượng",
      cta: "Khám phá sản phẩm",
      ctaSecondary: "Liên hệ",
      globalDesign: "Thiết kế toàn cầu",
      powerConverterLeader: "Trở thành đơn vị dẫn đầu về bộ chuyển đổi điện tử công suất",
      solutionsTitle: "Giải pháp",
      solutionsSubtitle: "Nhiều chế độ vận hành giúp đáp ứng linh hoạt các kịch bản khác nhau.",
      householdSolutionTitle: "Giải pháp lưu trữ năng lượng gia đình",
      householdSolutionDescription:
        "Chúng tôi cung cấp biến tần hybrid và pin gia đình có mật độ công suất cao, hiệu suất chuyển đổi cao, khả năng bảo vệ tin cậy, thông minh và ổn định cho nhiều nhu cầu sử dụng trong gia đình.",
      commercialSolutionTitle: "Lưu trữ năng lượng thương mại và công nghiệp",
      photovoltaicSolutionTitle: "Giải pháp hệ thống quang điện",
      rndTitle: "R&D và sản xuất",
      rndSubtitle: "Nghiên cứu và đổi mới, kiến tạo tương lai ngành điện",
      rndParagraph1: "Chúng tôi luôn xem chất lượng là nền tảng sống còn và phát triển.",
      rndParagraph2: "Doanh nghiệp đã đạt chứng nhận hệ thống quản lý chất lượng quốc tế ISO 9001.",
      rndParagraph3: "Sở hữu nhiều chứng nhận quốc tế, bao gồm hệ thống quản lý môi trường ISO 14001.",
      corporateNews: "Tin tức doanh nghiệp",
    },
    products: {
      title: "Sản phẩm",
      subtitle: "Giải pháp sáng tạo cho mọi ứng dụng năng lượng mặt trời",
      viewDetails: "Xem chi tiết",
      allCategories: "Tất cả danh mục",
      allProducts: "Tất cả sản phẩm",
      loading: "Đang tải sản phẩm...",
      noProducts: "Không tìm thấy sản phẩm trong danh mục này.",
      detailNotFound: "Không tìm thấy sản phẩm",
      backToProducts: "Quay lại sản phẩm",
      productImage: "Hình ảnh sản phẩm",
      keyFeatures: "Tính năng chính",
      requestQuote: "Yêu cầu báo giá",
      downloadDatasheet: "Tải datasheet",
      technicalSpecifications: "Thông số kỹ thuật",
      pvInverters: "Hệ thống quang điện",
      energyStorage: "Lưu trữ năng lượng công nghiệp và thương mại",
      hybridInverters: "Lưu trữ năng lượng gia đình",
    },
    company: {
      title: "Về chúng tôi",
      subtitle: "15+ năm đổi mới trong năng lượng tái tạo",
      heroTitle: "Về SolarTech Energy",
      heroSubtitle:
        "15+ năm đổi mới trong năng lượng tái tạo, cung cấp giải pháp năng lượng mặt trời đẳng cấp thế giới cho đối tác toàn cầu.",
      storyTitle: "Câu chuyện của chúng tôi",
      storyP1:
        "Thành lập năm 2011, SolarTech Energy đã phát triển từ một nhóm R&D nhỏ thành nhà sản xuất biến tần năng lượng mặt trời và hệ thống lưu trữ năng lượng hàng đầu.",
      storyP2:
        "Với hơn 500 nhân sự, nhà máy hiện đại và hiện diện tại hơn 30 quốc gia, chúng tôi tiếp tục thúc đẩy công nghệ năng lượng tái tạo.",
      partnerCta: "Hợp tác với chúng tôi",
      journeyTitle: "Hành trình phát triển",
      certificationsTitle: "Chứng nhận và tiêu chuẩn",
      certificationsSubtitle:
        "Sản phẩm của chúng tôi đáp ứng các tiêu chuẩn quốc tế cao về an toàn và chất lượng.",
      milestone2011: "Thành lập công ty tại Thành phố Hồ Chí Minh",
      milestone2014: "Đạt mốc 1 GW biến tần xuất xưởng toàn cầu",
      milestone2017: "Ra mắt dòng sản phẩm lưu trữ năng lượng",
      milestone2019: "Đạt chứng nhận TÜV Rheinland",
      milestone2022: "Mở rộng tới hơn 30 quốc gia",
      milestone2025: "Vượt mốc 10 GW tổng công suất giao hàng toàn cầu",
    },
    contact: {
      title: "Liên hệ",
      subtitle: "Liên hệ với đội ngũ của chúng tôi",
      name: "Họ và tên",
      email: "Email",
      phone: "Số điện thoại",
      subject: "Chủ đề",
      message: "Nội dung",
      send: "Gửi tin nhắn",
      heroSubtitle:
        "Liên hệ với đội ngũ kinh doanh và kỹ thuật để được tư vấn giải pháp phù hợp.",
      information: "Thông tin liên hệ",
      address: "Địa chỉ",
      businessHours: "Giờ làm việc",
      mondayFriday: "Thứ Hai - Thứ Sáu",
      saturday: "Thứ Bảy",
      sunday: "Chủ Nhật",
      closed: "Đóng cửa",
      sendUsMessage: "Gửi tin nhắn cho chúng tôi",
      success:
        "Tin nhắn của bạn đã được gửi thành công! Chúng tôi sẽ phản hồi trong vòng 24 giờ.",
      error: "Gửi tin nhắn thất bại. Vui lòng thử lại sau.",
      sending: "Đang gửi...",
      namePlaceholder: "Nguyễn Văn A",
      emailPlaceholder: "email@congty.com",
      subjectPlaceholder: "Tư vấn sản phẩm",
      messagePlaceholder: "Hãy cho chúng tôi biết yêu cầu dự án của bạn...",
    },
    common: {
      learnMore: "Tìm hiểu thêm",
      readMore: "Đọc thêm",
      download: "Tải xuống",
      loading: "Đang tải...",
      more: "Xem thêm",
      new: "MỚI",
      selectLanguage: "Chọn ngôn ngữ",
      toggleMenu: "Mở menu",
    },
    news: {
      title: "Tin tức và cập nhật",
      subtitle: "Cập nhật các sản phẩm mới, chứng nhận và xu hướng ngành.",
      noArticles: "Chưa có bài viết tin tức.",
      productLaunch: "Ra mắt sản phẩm",
      certification: "Chứng nhận",
      industryNews: "Tin ngành",
      partnership: "Hợp tác",
      events: "Sự kiện",
    },
    support: {
      title: "Hỗ trợ kỹ thuật",
      subtitle: "Truy cập tài liệu sản phẩm, tải xuống, đào tạo và hỗ trợ kỹ thuật.",
      directTitle: "Cần hỗ trợ trực tiếp?",
      directText:
        "Đội ngũ hỗ trợ kỹ thuật luôn sẵn sàng hỗ trợ lắp đặt, vận hành và xử lý sự cố.",
      contactTeam: "Liên hệ đội hỗ trợ",
      callHotline: "Gọi hotline",
      datasheetsTitle: "Datasheet sản phẩm",
      datasheetsDescription:
        "Tải thông số kỹ thuật và datasheet chi tiết cho các sản phẩm biến tần và lưu trữ.",
      datasheetsAction: "Xem datasheet",
      manualsTitle: "Hướng dẫn lắp đặt",
      manualsDescription:
        "Tài liệu hướng dẫn từng bước và sơ đồ đấu nối để lắp đặt an toàn, hiệu quả.",
      manualsAction: "Xem hướng dẫn",
      softwareTitle: "Phần mềm và firmware",
      softwareDescription:
        "Tải phần mềm giám sát, firmware mới nhất và công cụ cấu hình.",
      softwareAction: "Tải phần mềm",
      videosTitle: "Video hướng dẫn",
      videosDescription:
        "Xem video lắp đặt, xử lý sự cố và giới thiệu sản phẩm.",
      videosAction: "Xem video",
      faqTitle: "FAQ",
      faqDescription: "Tìm câu trả lời cho các câu hỏi thường gặp về sản phẩm và dịch vụ.",
      faqAction: "Xem FAQ",
      trainingTitle: "Chương trình đào tạo",
      trainingDescription:
        "Đăng ký các buổi đào tạo trực tuyến và trực tiếp cho kỹ thuật viên, kỹ sư.",
      trainingAction: "Đăng ký ngay",
    },
    footer: {
      contactNow: "Liên hệ ngay",
      name: "Tên",
      telephone: "Điện thoại",
      counseling: "Nội dung tư vấn",
      sending: "Gửi",
      hotline: "Hotline",
    },
  },
  zh: {
    nav: {
      home: "首页",
      products: "产品",
      company: "公司",
      news: "新闻",
      support: "支持",
      contact: "联系",
      aboutUs: "关于我们",
      solutions: "解决方案",
      productsCenter: "产品中心",
      rnd: "研发与制造",
      solutionHousehold: "家庭储能解决方案",
      solutionCommercial: "工商业储能",
      solutionPhotovoltaic: "光伏系统解决方案",
      rndCapabilities: "研发能力",
      batchProduction: "批量生产能力",
      qualityAssurance: "质量保证",
      technicalSupport: "技术支持",
      postSale: "售后服务",
      dataDownload: "资料下载",
    },
    home: {
      heroTitle: "用清洁能源驱动未来",
      heroSubtitle: "高效太阳能逆变器和储能系统的领先制造商",
      cta: "探索产品",
      ctaSecondary: "联系我们",
      globalDesign: "全球设计",
      powerConverterLeader: "成为电力电子变换器领导者",
      solutionsTitle: "解决方案",
      solutionsSubtitle: "多种工作模式可灵活应对不同场景。",
      householdSolutionTitle: "家庭储能解决方案",
      householdSolutionDescription:
        "我们提供高功率密度、高转换效率、可靠保护、智能稳定的混合逆变器和家用电池，适用于家庭节能、别墅供电、阳台光伏和离网场景。",
      commercialSolutionTitle: "工商业储能",
      photovoltaicSolutionTitle: "光伏系统解决方案",
      rndTitle: "研发与制造",
      rndSubtitle: "研发创新，锻造电力未来",
      rndParagraph1: "我们始终将质量视为生存和发展的核心。",
      rndParagraph2: "已通过 ISO 9001 国际质量管理体系认证。",
      rndParagraph3: "拥有包括 ISO 14001 环境管理体系在内的多项国际认证。",
      corporateNews: "企业新闻",
    },
    products: {
      title: "产品",
      subtitle: "适用于各种太阳能应用的创新解决方案",
      viewDetails: "查看详情",
      allCategories: "所有类别",
      allProducts: "所有产品",
      loading: "正在加载产品...",
      noProducts: "该类别暂无产品。",
      detailNotFound: "未找到产品",
      backToProducts: "返回产品",
      productImage: "产品图片",
      keyFeatures: "核心特点",
      requestQuote: "获取报价",
      downloadDatasheet: "下载数据表",
      technicalSpecifications: "技术规格",
      pvInverters: "光伏系统",
      energyStorage: "工商业储能",
      hybridInverters: "家庭储能",
    },
    company: {
      title: "关于我们",
      subtitle: "15年以上可再生能源创新",
      heroTitle: "关于 SolarTech Energy",
      heroSubtitle: "15年以上可再生能源创新，为全球合作伙伴提供可信赖的太阳能解决方案。",
      storyTitle: "我们的故事",
      storyP1:
        "SolarTech Energy 成立于 2011 年，已从小型研发团队成长为领先的太阳能逆变器和储能系统制造商。",
      storyP2: "凭借 500 多名员工、现代化制造设施以及覆盖 30 多个国家的业务网络，我们持续推动可再生能源技术发展。",
      partnerCta: "成为合作伙伴",
      journeyTitle: "发展历程",
      certificationsTitle: "认证与标准",
      certificationsSubtitle: "我们的产品符合最高的国际安全和质量标准。",
      milestone2011: "公司在胡志明市成立",
      milestone2014: "全球逆变器出货量达到 1 GW",
      milestone2017: "推出储能产品线",
      milestone2019: "获得 TÜV Rheinland 认证",
      milestone2022: "业务扩展至全球 30 多个国家",
      milestone2025: "全球累计出货超过 10 GW",
    },
    contact: {
      title: "联系我们",
      subtitle: "联系我们的团队",
      name: "姓名",
      email: "电子邮件",
      phone: "电话",
      subject: "主题",
      message: "信息",
      send: "发送消息",
      heroSubtitle: "联系我们的销售和技术团队，获取适合您的解决方案。",
      information: "联系信息",
      address: "地址",
      businessHours: "营业时间",
      mondayFriday: "周一至周五",
      saturday: "周六",
      sunday: "周日",
      closed: "休息",
      sendUsMessage: "发送消息",
      success: "您的消息已成功发送！我们将在24小时内回复。",
      error: "消息发送失败，请稍后重试。",
      sending: "发送中...",
      namePlaceholder: "张三",
      emailPlaceholder: "name@company.com",
      subjectPlaceholder: "产品咨询",
      messagePlaceholder: "请告诉我们您的项目需求...",
    },
    common: {
      learnMore: "了解更多",
      readMore: "阅读更多",
      download: "下载",
      loading: "加载中...",
      more: "更多",
      new: "新品",
      selectLanguage: "选择语言",
      toggleMenu: "打开菜单",
    },
    news: {
      title: "新闻与动态",
      subtitle: "了解最新产品发布、认证和行业洞察。",
      noArticles: "暂无新闻文章。",
      productLaunch: "产品发布",
      certification: "认证",
      industryNews: "行业新闻",
      partnership: "合作伙伴",
      events: "活动",
    },
    support: {
      title: "技术支持",
      subtitle: "获取产品文档、下载资源、培训和专家技术支持。",
      directTitle: "需要直接支持？",
      directText: "我们的技术支持团队可协助您完成安装、调试和故障排查。",
      contactTeam: "联系支持团队",
      callHotline: "拨打热线",
      datasheetsTitle: "产品数据表",
      datasheetsDescription: "下载所有逆变器和储能产品的详细技术规格与数据表。",
      datasheetsAction: "浏览数据表",
      manualsTitle: "安装手册",
      manualsDescription: "安全高效安装所需的分步指南和接线图。",
      manualsAction: "查看手册",
      softwareTitle: "软件与固件",
      softwareDescription: "下载最新监控软件、固件更新和配置工具。",
      softwareAction: "下载软件",
      videosTitle: "视频教程",
      videosDescription: "观看安装、故障排查和产品演示视频。",
      videosAction: "观看视频",
      faqTitle: "常见问题",
      faqDescription: "查找关于产品和服务的常见问题答案。",
      faqAction: "查看 FAQ",
      trainingTitle: "培训项目",
      trainingDescription: "报名面向安装人员和工程师的线上及线下技术培训。",
      trainingAction: "立即报名",
    },
    footer: {
      contactNow: "立即联系",
      name: "姓名",
      telephone: "电话",
      counseling: "咨询内容",
      sending: "发送",
      hotline: "热线",
    },
  },
  de: {
    nav: {
      home: "Startseite",
      products: "Produkte",
      company: "Unternehmen",
      news: "Nachrichten",
      support: "Support",
      contact: "Kontakt",
      aboutUs: "Ueber uns",
      solutions: "Loesungen",
      productsCenter: "Produktzentrum",
      rnd: "F&E und Fertigung",
      solutionHousehold: "Energiespeicherloesungen fuer Haushalte",
      solutionCommercial: "Gewerbliche und industrielle Energiespeicherung",
      solutionPhotovoltaic: "Photovoltaik-Systemloesungen",
      rndCapabilities: "F&E-Faehigkeiten",
      batchProduction: "Serienproduktionsfaehigkeiten",
      qualityAssurance: "Qualitaetssicherung",
      technicalSupport: "Technischer Support",
      postSale: "After-Sales-Service",
      dataDownload: "Daten-Download",
    },
    home: {
      heroTitle: "Die Zukunft mit sauberer Energie antreiben",
      heroSubtitle:
        "Fuehrender Hersteller von Solarwechselrichtern und Energiespeichersystemen",
      cta: "Produkte entdecken",
      ctaSecondary: "Kontakt",
      globalDesign: "Globales Design",
      powerConverterLeader: "Fuehrend bei Leistungselektronik-Wandlern werden",
      solutionsTitle: "Loesungen",
      solutionsSubtitle: "Mehrere Betriebsmodi reagieren flexibel auf unterschiedliche Szenarien.",
      householdSolutionTitle: "Energiespeicherloesungen fuer Haushalte",
      householdSolutionDescription:
        "Wir bieten Hybridwechselrichter und Haushaltsbatterien mit hoher Leistungsdichte, hoher Effizienz, zuverlaessigem Schutz, Intelligenz und Stabilitaet fuer verschiedene Heim- und Off-Grid-Anwendungen.",
      commercialSolutionTitle: "Gewerbliche und industrielle Energiespeicherung",
      photovoltaicSolutionTitle: "Photovoltaik-Systemloesungen",
      rndTitle: "F&E und Fertigung",
      rndSubtitle: "Forschung und Innovation fuer die Zukunft der Energie",
      rndParagraph1: "Qualitaet ist fuer uns die Grundlage fuer Bestand und Wachstum.",
      rndParagraph2: "Wir haben die internationale ISO 9001 Qualitaetsmanagement-Zertifizierung erhalten.",
      rndParagraph3: "Wir halten mehrere internationale Zertifizierungen, darunter ISO 14001.",
      corporateNews: "Unternehmensnachrichten",
    },
    products: {
      title: "Produkte",
      subtitle: "Innovative Loesungen fuer jede Solaranwendung",
      viewDetails: "Details ansehen",
      allCategories: "Alle Kategorien",
      allProducts: "Alle Produkte",
      loading: "Produkte werden geladen...",
      noProducts: "Keine Produkte in dieser Kategorie gefunden.",
      detailNotFound: "Produkt nicht gefunden",
      backToProducts: "Zurueck zu Produkten",
      productImage: "Produktbild",
      keyFeatures: "Hauptmerkmale",
      requestQuote: "Angebot anfordern",
      downloadDatasheet: "Datenblatt herunterladen",
      technicalSpecifications: "Technische Daten",
      pvInverters: "Photovoltaik-System",
      energyStorage: "Gewerbliche und industrielle Energiespeicherung",
      hybridInverters: "Energiespeicher fuer Haushalte",
    },
    company: {
      title: "Ueber uns",
      subtitle: "15+ Jahre Innovation in erneuerbarer Energie",
      heroTitle: "Ueber SolarTech Energy",
      heroSubtitle:
        "15+ Jahre Innovation in erneuerbarer Energie mit weltweiten Solar-Loesungen fuer Partner.",
      storyTitle: "Unsere Geschichte",
      storyP1:
        "Seit der Gruendung 2011 ist SolarTech Energy von einem kleinen F&E-Team zu einem fuehrenden Hersteller von Solarwechselrichtern und Energiespeichern gewachsen.",
      storyP2:
        "Mit mehr als 500 Mitarbeitenden, modernen Produktionsanlagen und Praesenz in ueber 30 Laendern treiben wir erneuerbare Energietechnologie voran.",
      partnerCta: "Partner werden",
      journeyTitle: "Unsere Entwicklung",
      certificationsTitle: "Zertifizierungen und Standards",
      certificationsSubtitle: "Unsere Produkte erfuellen hoechste internationale Sicherheits- und Qualitaetsstandards.",
      milestone2011: "Unternehmen in Ho-Chi-Minh-Stadt gegruendet",
      milestone2014: "Erste 1 GW Wechselrichter weltweit ausgeliefert",
      milestone2017: "Energiespeicher-Produktlinie eingefuehrt",
      milestone2019: "TÜV Rheinland Zertifizierung erhalten",
      milestone2022: "Expansion in ueber 30 Laender",
      milestone2025: "Mehr als 10 GW weltweit ausgeliefert",
    },
    contact: {
      title: "Kontakt",
      subtitle: "Kontaktieren Sie unser Team",
      name: "Vollstaendiger Name",
      email: "E-Mail-Adresse",
      phone: "Telefonnummer",
      subject: "Betreff",
      message: "Nachricht",
      send: "Nachricht senden",
      heroSubtitle: "Kontaktieren Sie unser Vertriebs- und Technikteam fuer die passende Loesung.",
      information: "Kontaktinformationen",
      address: "Adresse",
      businessHours: "Geschaeftszeiten",
      mondayFriday: "Montag - Freitag",
      saturday: "Samstag",
      sunday: "Sonntag",
      closed: "Geschlossen",
      sendUsMessage: "Senden Sie uns eine Nachricht",
      success: "Ihre Nachricht wurde erfolgreich gesendet. Wir melden uns innerhalb von 24 Stunden.",
      error: "Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es spaeter erneut.",
      sending: "Wird gesendet...",
      namePlaceholder: "Max Mustermann",
      emailPlaceholder: "max@firma.com",
      subjectPlaceholder: "Produktanfrage",
      messagePlaceholder: "Beschreiben Sie Ihre Projektanforderungen...",
    },
    common: {
      learnMore: "Mehr erfahren",
      readMore: "Weiterlesen",
      download: "Herunterladen",
      loading: "Wird geladen...",
      more: "Mehr",
      new: "NEU",
      selectLanguage: "Sprache auswaehlen",
      toggleMenu: "Menue oeffnen",
    },
    news: {
      title: "Nachrichten und Updates",
      subtitle: "Aktuelle Produktstarts, Zertifizierungen und Brancheneinblicke.",
      noArticles: "Keine Nachrichten verfuegbar.",
      productLaunch: "Produktstart",
      certification: "Zertifizierung",
      industryNews: "Branchennachrichten",
      partnership: "Partnerschaft",
      events: "Veranstaltungen",
    },
    support: {
      title: "Technischer Support",
      subtitle: "Produktdokumentation, Downloads, Schulungen und technische Hilfe.",
      directTitle: "Direkte Unterstuetzung benoetigt?",
      directText: "Unser Technikteam hilft bei Installation, Inbetriebnahme und Fehlersuche.",
      contactTeam: "Support-Team kontaktieren",
      callHotline: "Hotline anrufen",
      datasheetsTitle: "Produktdatenblaetter",
      datasheetsDescription: "Detaillierte technische Daten und Datenblaetter fuer alle Produkte herunterladen.",
      datasheetsAction: "Datenblaetter ansehen",
      manualsTitle: "Installationshandbuecher",
      manualsDescription: "Schritt-fuer-Schritt-Anleitungen und Schaltplaene fuer sichere Installation.",
      manualsAction: "Handbuecher ansehen",
      softwareTitle: "Software und Firmware",
      softwareDescription: "Aktuelle Monitoring-Software, Firmware und Konfigurationstools herunterladen.",
      softwareAction: "Software herunterladen",
      videosTitle: "Video-Tutorials",
      videosDescription: "Installations-, Fehlerbehebungs- und Produktvideos ansehen.",
      videosAction: "Videos ansehen",
      faqTitle: "FAQ",
      faqDescription: "Antworten auf haeufige Fragen zu Produkten und Services.",
      faqAction: "FAQ ansehen",
      trainingTitle: "Schulungsprogramme",
      trainingDescription: "Online- und Vor-Ort-Schulungen fuer Installateure und Ingenieure buchen.",
      trainingAction: "Jetzt anmelden",
    },
    footer: {
      contactNow: "Jetzt kontaktieren",
      name: "Name",
      telephone: "Telefon",
      counseling: "Beratung",
      sending: "Senden",
      hotline: "Hotline",
    },
  },
  es: {
    nav: {
      home: "Inicio",
      products: "Productos",
      company: "Empresa",
      news: "Noticias",
      support: "Soporte",
      contact: "Contacto",
      aboutUs: "Sobre nosotros",
      solutions: "Soluciones",
      productsCenter: "Centro de productos",
      rnd: "I+D y fabricacion",
      solutionHousehold: "Soluciones de almacenamiento para el hogar",
      solutionCommercial: "Almacenamiento comercial e industrial",
      solutionPhotovoltaic: "Soluciones de sistemas fotovoltaicos",
      rndCapabilities: "Capacidades de I+D",
      batchProduction: "Capacidades de produccion en serie",
      qualityAssurance: "Aseguramiento de calidad",
      technicalSupport: "Soporte tecnico",
      postSale: "Servicio posventa",
      dataDownload: "Descarga de datos",
    },
    home: {
      heroTitle: "Impulsando el futuro con energia limpia",
      heroSubtitle:
        "Fabricante lider de inversores solares y sistemas de almacenamiento de energia",
      cta: "Explorar productos",
      ctaSecondary: "Contacto",
      globalDesign: "Diseno global",
      powerConverterLeader: "Conviertase en lider en convertidores electronicos de potencia",
      solutionsTitle: "Soluciones",
      solutionsSubtitle: "Varios modos de trabajo responden con flexibilidad a diferentes escenarios.",
      householdSolutionTitle: "Soluciones de almacenamiento para el hogar",
      householdSolutionDescription:
        "Ofrecemos inversores hibridos y baterias domesticas con alta densidad de potencia, alta eficiencia, proteccion confiable, inteligencia y estabilidad para aplicaciones residenciales y fuera de red.",
      commercialSolutionTitle: "Almacenamiento comercial e industrial",
      photovoltaicSolutionTitle: "Soluciones de sistemas fotovoltaicos",
      rndTitle: "I+D y fabricacion",
      rndSubtitle: "Investigacion e innovacion para forjar el futuro de la electricidad",
      rndParagraph1: "Siempre consideramos la calidad como el nucleo de la supervivencia y el desarrollo.",
      rndParagraph2: "Hemos obtenido la certificacion internacional ISO 9001 de gestion de calidad.",
      rndParagraph3: "Contamos con multiples certificaciones internacionales, incluida ISO 14001.",
      corporateNews: "Noticias corporativas",
    },
    products: {
      title: "Productos",
      subtitle: "Soluciones innovadoras para cada aplicacion solar",
      viewDetails: "Ver detalles",
      allCategories: "Todas las categorias",
      allProducts: "Todos los productos",
      loading: "Cargando productos...",
      noProducts: "No se encontraron productos en esta categoria.",
      detailNotFound: "Producto no encontrado",
      backToProducts: "Volver a productos",
      productImage: "Imagen del producto",
      keyFeatures: "Caracteristicas principales",
      requestQuote: "Solicitar cotizacion",
      downloadDatasheet: "Descargar ficha tecnica",
      technicalSpecifications: "Especificaciones tecnicas",
      pvInverters: "Sistema fotovoltaico",
      energyStorage: "Almacenamiento comercial e industrial",
      hybridInverters: "Almacenamiento de energia para el hogar",
    },
    company: {
      title: "Sobre nosotros",
      subtitle: "15+ anos de innovacion en energia renovable",
      heroTitle: "Sobre SolarTech Energy",
      heroSubtitle:
        "15+ anos de innovacion en energia renovable, entregando soluciones solares de clase mundial para socios globales.",
      storyTitle: "Nuestra historia",
      storyP1:
        "Fundada en 2011, SolarTech Energy crecio de un pequeno equipo de I+D a un fabricante lider de inversores solares y sistemas de almacenamiento.",
      storyP2:
        "Con mas de 500 empleados, instalaciones modernas y presencia en mas de 30 paises, seguimos impulsando la tecnologia de energia renovable.",
      partnerCta: "Colabore con nosotros",
      journeyTitle: "Nuestro recorrido",
      certificationsTitle: "Certificaciones y normas",
      certificationsSubtitle: "Nuestros productos cumplen los mas altos estandares internacionales de seguridad y calidad.",
      milestone2011: "Empresa fundada en Ciudad Ho Chi Minh",
      milestone2014: "Primer 1 GW de inversores enviado globalmente",
      milestone2017: "Lanzamiento de la linea de almacenamiento de energia",
      milestone2019: "Certificacion TÜV Rheinland obtenida",
      milestone2022: "Expansion a mas de 30 paises",
      milestone2025: "Mas de 10 GW enviados a nivel mundial",
    },
    contact: {
      title: "Contacto",
      subtitle: "Pongase en contacto con nuestro equipo",
      name: "Nombre completo",
      email: "Correo electronico",
      phone: "Telefono",
      subject: "Asunto",
      message: "Mensaje",
      send: "Enviar mensaje",
      heroSubtitle: "Contacte con nuestro equipo comercial y tecnico para encontrar la solucion adecuada.",
      information: "Informacion de contacto",
      address: "Direccion",
      businessHours: "Horario de atencion",
      mondayFriday: "Lunes - Viernes",
      saturday: "Sabado",
      sunday: "Domingo",
      closed: "Cerrado",
      sendUsMessage: "Envienos un mensaje",
      success: "Su mensaje se ha enviado correctamente. Responderemos en 24 horas.",
      error: "No se pudo enviar el mensaje. Intentelo de nuevo mas tarde.",
      sending: "Enviando...",
      namePlaceholder: "Juan Perez",
      emailPlaceholder: "juan@empresa.com",
      subjectPlaceholder: "Consulta de producto",
      messagePlaceholder: "Cuentenos los requisitos de su proyecto...",
    },
    common: {
      learnMore: "Mas informacion",
      readMore: "Leer mas",
      download: "Descargar",
      loading: "Cargando...",
      more: "Mas",
      new: "NUEVO",
      selectLanguage: "Seleccionar idioma",
      toggleMenu: "Abrir menu",
    },
    news: {
      title: "Noticias y actualizaciones",
      subtitle: "Mantengase informado sobre lanzamientos, certificaciones y tendencias del sector.",
      noArticles: "No hay noticias disponibles.",
      productLaunch: "Lanzamiento",
      certification: "Certificacion",
      industryNews: "Noticias del sector",
      partnership: "Alianza",
      events: "Eventos",
    },
    support: {
      title: "Soporte tecnico",
      subtitle: "Acceda a documentacion, descargas, capacitacion y soporte tecnico experto.",
      directTitle: "Necesita soporte directo?",
      directText: "Nuestro equipo tecnico puede ayudarle con instalacion, puesta en marcha y solucion de problemas.",
      contactTeam: "Contactar soporte",
      callHotline: "Llamar hotline",
      datasheetsTitle: "Fichas tecnicas",
      datasheetsDescription: "Descargue especificaciones tecnicas y fichas de todos los productos.",
      datasheetsAction: "Ver fichas",
      manualsTitle: "Manuales de instalacion",
      manualsDescription: "Guias paso a paso y diagramas para una instalacion segura y eficiente.",
      manualsAction: "Ver manuales",
      softwareTitle: "Software y firmware",
      softwareDescription: "Descargue software de monitoreo, firmware y herramientas de configuracion.",
      softwareAction: "Descargar software",
      videosTitle: "Video tutoriales",
      videosDescription: "Vea videos de instalacion, solucion de problemas y demostraciones.",
      videosAction: "Ver videos",
      faqTitle: "FAQ",
      faqDescription: "Encuentre respuestas a preguntas frecuentes sobre productos y servicios.",
      faqAction: "Ver FAQ",
      trainingTitle: "Programas de capacitacion",
      trainingDescription: "Registrese en capacitaciones tecnicas online y presenciales.",
      trainingAction: "Registrarse",
    },
    footer: {
      contactNow: "Contactenos ahora",
      name: "Nombre",
      telephone: "Telefono",
      counseling: "Consulta",
      sending: "Enviar",
      hotline: "Hotline",
    },
  },
} as const;

type Locale = keyof typeof translations;
const DEFAULT_LOCALE: Locale = "en";

interface LanguageContextValue {
  locale: Locale;
  t: (key: string) => string;
  switchLanguage: (lang: Locale) => void;
  availableLocales: Locale[];
}

function getNestedTranslation(source: unknown, keys: string[]): string | undefined {
  let value = source;

  for (const key of keys) {
    if (!value || typeof value !== "object" || !(key in value)) {
      return undefined;
    }

    value = (value as Record<string, unknown>)[key];
  }

  return typeof value === "string" ? value : undefined;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(DEFAULT_LOCALE);

  useEffect(() => {
    const savedLocale = window.localStorage.getItem("site-locale");
    if (savedLocale && savedLocale in translations) {
      const timer = window.setTimeout(() => {
        setLocale(savedLocale as Locale);
      }, 0);

      return () => window.clearTimeout(timer);
    }
  }, []);

  const t = useCallback(
    (key: string) => {
      const keys = key.split(".");
      return (
        getNestedTranslation(translations[locale], keys) ||
        getNestedTranslation(translations.en, keys) ||
        key
      );
    },
    [locale]
  );

  const switchLanguage = useCallback((lang: Locale) => {
    if (translations[lang]) {
      setLocale(lang);
      window.localStorage.setItem("site-locale", lang);
    }
  }, []);

  return (
    <LanguageContext.Provider
      value={{
        locale,
        t,
        switchLanguage,
        availableLocales: ["zh", "en", "vi", "de", "es"],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export default LanguageContext;
